### ISSUE TITLE
Issues two requests to server for same video file (cookies not included)

### ISSUE THREAD

**Issue by jemunk** [Baseflow/XamarinMediaManager#460]
## 🐛 Bug Report

In Xamarin Forms on Android I am using the CrossMediaManager.Current.RequestHeaders to set the cookies required for authenticating against the server. I got some help in #456 on that, thanks!

But now I see some really strange stuff in the communication. In the console i get this:
> E/ExoPlayerImplInternal(17164): com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403

Analyzing the TCP communication in WireShark reveals that the video file is requested two times. The first time with the user-agent of the phone, with the cookies I've set, which seems to be retrieved successfully. The second time it is the user-agent of MediaManager, but without the required cookies, which then causes the 403 error.

I am using latest 0.5.3 on .Net Standard

Here comes a recap of the communication:

```
Req/Resp 1 (User-Agent: Sony; Includes the cookies supplied for authentication)

GET /Blob/Download/3533d55ab6054536b8cd654b92709b07JvhgLTDVRf HTTP/1.1
User-Agent: SonyE6653 Build/32.4.A.1.54 stagefright/1.2 (Linux;Android 7.1.1)
cookie: ASP.NET_SessionId=(removed); FedAuth=(removed)
Host: 192.168.1.238
Connection: Keep-Alive
Accept-Encoding: gzip

HTTP/1.1 200 OK
Cache-Control: private
Content-Length: 21069678
Content-Type: video/mp4
Content-Range: bytes 0-21069677/21069678
Accept-Ranges: 0-21069678
Server: Microsoft-IIS/10.0
Content-Disposition: attachment; filename=SampleVideo_1280x720_20mb%2520(1).mp4
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
Date: Thu, 25 Apr 2019 14:34:26 GMT

[Payload here, but not all as client aborts using TCP Resets, but continues in next request, controlled by the Range HTTP header]


Req/Resp 2 (User-Agent: Sony; requst for the last part using the Range HTTP header)

GET /Blob/Download/3533d55ab6054536b8cd654b92709b07JvhgLTDVRf HTTP/1.1
User-Agent: SonyE6653 Build/32.4.A.1.54 stagefright/1.2 (Linux;Android 7.1.1)
cookie: ASP.NET_SessionId=(removed); FedAuth=(removed)
Range: bytes=19953777-
Host: 192.168.1.238
Connection: Keep-Alive
Accept-Encoding: gzip

HTTP/1.1 206 Partial Content
Cache-Control: private
Content-Length: 1115901
Content-Type: video/mp4
Content-Range: bytes 19953777-21069677/21069678
Accept-Ranges: 0-21069678
Server: Microsoft-IIS/10.0
Content-Disposition: attachment; filename=SampleVideo_1280x720_20mb%2520(1).mp4
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
Date: Thu, 25 Apr 2019 14:34:30 GMT

[Remaining payload of file here]


But now something breaks! A new request for the same file, but with different user-agent and WITHOUT the cookies for authentication. Server responds 403 Forbidden because of the missing cookies.
Req/Resp 3-7

GET /Blob/Download/3533d55ab6054536b8cd654b92709b07JvhgLTDVRf HTTP/1.1
User-Agent: MediaManager/1.2 (Linux;Android 7.1.1) ExoPlayerLib/2.8.3
Accept-Encoding: identity
Host: 192.168.1.238
Connection: Keep-Alive

HTTP/1.1 403 Forbidden
Cache-Control: private
Content-Type: text/html
Server: Microsoft-IIS/10.0
Set-Cookie: ASP.NET_SessionId=21yepyld0emaxag2s2pmjnr0; domain=192.168.1.238; path=/; HttpOnly
X-AspNetMvc-Version: 5.2
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
Date: Thu, 25 Apr 2019 14:34:33 GMT
Content-Length: 1224
```

**Comment by martijn00** [comment]
@jemunk Do you have a url i can test with?

**Comment by jemunk** [comment]
@martijn00  It is rather tricky, as you need session cookies for accessing our site and for proving that the cookies are not attached to the HTTP headers.
But the url is https://www.speedadmin.dk/Blob/Download/13d630b1c2f34e08b0f802be0f0cd44bdGpSjLp8hL
I can supply you with session cookies valid for 8 hours if you mail me at jesper@speedware.dk

**Comment by martijn00** [comment]
Hmm that's a bit hard. Can you hook up the source code to your app and debug it?

There are 2 places the headers are used: https://github.com/martijn00/XamarinMediaManager/blob/develop/MediaManager/Platforms/Android/Media/MediaPlayer.cs#L105 and https://github.com/martijn00/XamarinMediaManager/blob/develop/MediaManager/Platforms/Android/MediaExtractor.cs#L59

Could you see any reason why those are not used the 2nd time?

**Comment by jemunk** [comment]
Sorry, but I don't know how to hook up the source code. I also looked into the sources which seems ok, but I can't understand the big picture of it.
It is the same issue for audio as well.
If you have a protocol analyzer like WireShark, and put a "cookie" header into the request, you should be able to reproduce it.

**Comment by martijn00** [comment]
Any more info on this?

It seems a bit related to https://medium.com/@thesultanster/multiple-exomedia-players-using-akamai-hls-streams-16dd0788e41d

Another option i just though of is the metadata extractor: https://github.com/martijn00/XamarinMediaManager/blob/develop/MediaManager/Platforms/Android/Media/MediaItemExtensions.cs#L177

Maybe a second client is used somewhere. If you provide metadata yourself and set IsMetadataExtracted to true, does it work then?

**Comment by vynxcc** [comment]
I have same issue
