### ISSUE TITLE
Unable to stream video from https where credentials are required

### ISSUE THREAD

**Issue by KMWenyon** [Baseflow/XamarinMediaManager#503]
## 🐛 Bug Report

As a corporate user I need to be able to view videos that sit behind a corporate firewall and require NTLM Authentication to access and stream the MP4 video.

### Expected behavior
To be able to intercept the authentication challenge and be able to provide credentials and allow access to the protected resource to view the video.  To be able to override http client or NEUrlSessionDelegate and/or set credentials in http client.

### Configuration
VS for Mac 7.8.2 build 2
MacOS 10.13.6
Xamarin Forms 4.0.0.482894
MediaManager 0.6.7

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ X] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
You can use the RequestHeaders to set auth headers. Since all platforms use a different http client i think intercepting that will be hard. Can you use the RequestHeaders?

**Comment by KMWenyon** [comment]
Not sure I can add NTLM Credentials in in the request headers (Dictionary), at least I do not know how, do you know a link?

Otherwise, in the case of iOS, would it be possible in the platform implementation of the MediaManager to set or expose a way add a custom session delegate.  If not provided the current behavior, if set, the developer could include their desired behavior in the delegate the exposed method could take a INSUrlSessionDelegate (some interface that can implement URLSession:didReceiveChallenge:completionHandler: )

You Could:
MediaManagerImpl.SetSessionDelegate(INSUrlSessionDelegate nsUrlSessionDelegate);

I Could:

I would create a delegate something this this:
CustomNSUrlSessionDelegate _customNSUrlSessionDelegate = new CustomNSUrlSessionDelegate();

MediaManagerImpl.SetSessionDelegate(_customNSUrlSessionDelegate);

Using the sample delegate below...
public class CustomNSUrlSessionDelegate : NSObject, INSUrlSessionDelegate
    {
        #region " Public Methods and Functions... "

        /// <summary>
        /// DidBecomeInvalid implementation.
        /// </summary>
        /// <param name="session">The ns url session.</param>
        /// <param name="error">The ns error</param>
        [Export("URLSession:didBecomeInvalidWithError:")]
        public void DidBecomeInvalid(NSUrlSession session, NSError error)
        {
            string sessionText = session?.ToString();
            System.Diagnostics.Debug.WriteLine("CgNSUrlSessionDelegate.DidBecomeInvalid Session: " + sessionText);

            string errorText = error?.ToString();
            System.Diagnostics.Debug.WriteLine("CgNSUrlSessionDelegate.DidBecomeInvalid Error: " + errorText);
        }

        /// <summary>
        /// DidFinishEventsForBackgroundSession implementation.
        /// </summary>
        /// <param name="session">The ns url session.</param>
        [Export("URLSessionDidFinishEventsForBackgroundURLSession:")]
        public void DidFinishEventsForBackgroundSession(NSUrlSession session)
        {
            string sessionText = session?.ToString();
            System.Diagnostics.Debug.WriteLine("CgNSUrlSessionDelegate.DidFinishEventsForBackgroundSession Session: " + sessionText);
        }

        /// <summary>
        /// DidReceiveChallenge implementation.
        /// </summary>
        /// <param name="session">The session.</param>
        /// <param name="challenge">The challenge.</param>
        /// <param name="completionHandler">The completion handler.</param>
        [Export("URLSession:didReceiveChallenge:completionHandler:")]
        **public void DidReceiveChallenge(NSUrlSession session, NSUrlAuthenticationChallenge challenge, Action<NSUrlSessionAuthChallengeDisposition, NSUrlCredential> completionHandler)**
        {
            string authMethod = challenge.ProtectionSpace.AuthenticationMethod;
            Console.WriteLine("Auth method in use: {0}", authMethod);

            if ((challenge != null) && (challenge.PreviousFailureCount > 0))
            {
                string message = String.Format("Login for {0} has failed, please reset and re-enter your credentials", challenge.ProposedCredential.User);
                System.Diagnostics.Debug.WriteLine(message);
                // TODO KMW: Show message to user, cancel auth, abort the request, clear navigation stack and show user sign-in dialog
                // Cancel the authentication challenge
                completionHandler(NSUrlSessionAuthChallengeDisposition.CancelAuthenticationChallenge, null);
                //// Abort the request
                //OnAbortRequest();
            }
            else if (authMethod.Equals(NSUrlProtectionSpace.AuthenticationMethodHTTPBasic) ||
                     authMethod.Equals(NSUrlProtectionSpace.AuthenticationMethodHTTPDigest) ||
                     authMethod.Equals(NSUrlProtectionSpace.AuthenticationMethodNTLM) ||
                     authMethod.Equals(NSUrlProtectionSpace.AuthenticationMethodNegotiate))
            {
                //DisplayAuthQueryDialog(challenge);

                // Setup the credentials using session cache (in memory)
                NSUrlCredential credential = NSUrlCredential.FromUserPasswordPersistance(AppSettingsService.CachedUserName, AppSettingsService.CachedUserPassword, NSUrlCredentialPersistence.ForSession);
                completionHandler(NSUrlSessionAuthChallengeDisposition.UseCredential, credential);
            }
            else if (authMethod.Equals(NSUrlProtectionSpace.AuthenticationMethodClientCertificate))
            {
                // Do nothing 
            }
            else if (authMethod.Equals(NSUrlProtectionSpace.AuthenticationMethodServerTrust))
            {
                // Setup the credentials using session cache (in memory)
                NSUrlCredential credential = NSUrlCredential.FromUserPasswordPersistance(AppSettingsService.CachedUserName, AppSettingsService.CachedUserPassword, NSUrlCredentialPersistence.ForSession);
                completionHandler(NSUrlSessionAuthChallengeDisposition.UseCredential, credential);
            }
            else
            {
                //// This application doesn't support the specified method
                //DispatchQueue.MainQueue.DispatchAsync(() => OnDownloadDone(null));
            }

            //// Reset the buffer
            //_dataBuffer.Length = 0;
        }
        
        #endregion
}

**Comment by KMWenyon** [comment]
Is this still closed after providing the comments above?

**Comment by martijn00** [comment]
What about:

```
byte[] authBytes = Encoding.UTF8.GetBytes(_account.Username + ":" + _account.Password); CrossMediaManager.Current.RequestHeaders.Add("Authorization", "BASIC " + Convert.ToBase64String(authBytes));
```

A simple google search gives me plenty of options to use headers. I don't see a possibility any easy way to add custom http clients at the moment. It would probably be possible to add this as a paid project if you are interested. You can email me for that.

**Comment by KMWenyon** [comment]
Isn't Basic and NTLM authentication different? the same for the header syntax and the calculation of the NTLM auth token hash?

I do not want to use a custom http client per say... How about adding a static method on the platform implementation of the MediaManager to set a custom session delegate?

This could be a feature that other would be interested in if they needed to view content that is password protected or sits behind a protected resource?

**Comment by KMWenyon** [comment]
Thank you for your suggestion, I did try your suggestion without any success, the video still does not load:

byte[] authBytes = Encoding.UTF8.GetBytes(_account.Username + ":" + _account.Password);
CrossMediaManager.Current.RequestHeaders.Add("Authorization", "BASIC " + Convert.ToBase64String(authBytes));

I have implemented the following events and only see the Status changed to paused

MediaManager.BufferedChanged += Current_BufferedChanged;
                MediaManager.MediaItemChanged += Current_MediaItemChanged;
                MediaManager.MediaItemFailed += Current_MediaItemFailed;
                MediaManager.MediaItemFinished += Current_MediaItemFinished;
                MediaManager.PositionChanged += Current_PositionChanged;
                MediaManager.StateChanged += MediaManager_StateChanged;

**Comment by martijn00** [comment]
Check this thread: https://forums.xamarin.com/discussion/comment/144229/#Comment_144229

For iOS this one might work if the headers don't work: https://docs.microsoft.com/en-us/dotnet/api/avfoundation.avassetdownloaddelegate.didreceivechallenge?view=xamarin-ios-sdk-12

For Android maybe: https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/upstream/DefaultBandwidthMeter.html#onTransferStart-com.google.android.exoplayer2.upstream.DataSource-com.google.android.exoplayer2.upstream.DataSpec-boolean-

But the docs are very unclear on all of this. I don't think i have a lot of time for this right now, so i am happy to take a PR, or provide commercial support on this.

**Comment by OdetteP** [comment]
Did you solve this issue?
