### ISSUE TITLE
[Android] Activity not disposed after onDestroy when playing

### ISSUE THREAD

**Issue by valentin-debris** [Baseflow/XamarinMediaManager#513]
## 🐛 Bug Report

Hi. For Android, I want to destroy the app when the user clear it (when he drag it to remove it from the app in memory), but if the player is running, I can't.
If when in foreground, he press a button that call CrossMediaManager.Current.Stop(); the clear works, but if the player is running, the notif if there so it keeps the app in backgroud. 
If I press the "stop" btn in the notif or try to call CrossMediaManager.Current.Stop(); in onDestroy or onStop, it remove the notif but the app is still in background. This cause problem when I reopen the app then, it's not a real restart so some data are missing.

I noticed that when debugging, in VS, the debug process is still running.

### Expected behavior
Like iOS, we should be able to force the app to stop when remove it from the apps in memory.

### Reproduction steps
Run the app in debug, start playing a song, remove the app from running. Stop the song from the notif. The process is still running.

Repo to reproduce : https://github.com/valentin-debris/XamarinMediaDebug/tree/0.6.7-app_running

### Configuration

**Version:** 0.6.7

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
I've tried this in the sample in this repo, but not sure what you mean. When calling stop the Foreground service is stopped and things are disposed. Where is the problem?

**Comment by valentin-debris** [comment]
@martijn00 I made a quick commit to the repo to help you tu understand. I added a static property in App.xaml.cs (nbLaunch = 1) which I update every time the MainPage is called and display it "Instance number : VALUE_HERE)
If the app is fully destroyed, nbLaunch should be =1 when start the app. But if you follow the process, when you restart the app, the value is now 2. (I'm currently trying to make a record of my screen to show you).

**Comment by valentin-debris** [comment]
@martijn00 here the [quick demo](https://drive.google.com/file/d/18nlFOfNuDbC9wIa5CiwkZf2bdXM1gtle/view?usp=sharing) : 
As you can see, the "instance number" increase, meaning the app is not fully destroyed. But if I then restart and close it again without starting a song, it is reset to 1, meaning fully destroyed.

**Comment by valentin-debris** [comment]
@martijn00 , did you take I look ?

A tried to debug and when I comment this line https://github.com/martijn00/XamarinMediaManager/blob/develop/MediaManager/Platforms/Android/MediaSession/MediaBrowserService.cs#L78, the app is fully destroyed. So my assumption is when the StopForeground is called, it may try to use references that have been cleared and so, it can't stop the service.

**Comment by martijn00** [comment]
@valentin-debris See https://github.com/martijn00/XamarinMediaManager/issues/517#issuecomment-507771685

Does that help you when you call that onDestroy of the activity?

**Comment by valentin-debris** [comment]
@martijn00 , no still not working.

I tried differents thing in MainActivity.cs as the following but the OnDestroy is never call.

```
protected override void OnDestroy()
        {
            base.OnDestroy();
            //CrossMediaManager.Current.Stop();
            var intent = new Intent(ApplicationContext, Java.Lang.Class.FromType(typeof(MediaManager.Platforms.Android.MediaSession.MediaBrowserService)));
            StopService(intent);
            //intent.Dispose();// Tried too, not working
        }
```

Do I miss something ?!

**Comment by martijn00** [comment]
Try onPause then. If destroy is not called something else might also be wrong in your app.

**Comment by valentin-debris** [comment]
@martijn00 , it's the onDestroy() in MediaBrowserService that is never call, the one in MainActivity.cs is call every time I kill the app.

**Comment by martijn00** [comment]
The onDestroy of the MediaBrowserService is not supposed to be called at that moment. It is a foreground service, otherwise the music would stop playing when you go out the app.

**Comment by valentin-debris** [comment]
@martijn00 , this is what I'm trying to do. 
Like Spotify, when you kill the app, even if the song is playing, it stop and close the app. This is not possible with the MediaPlayer, because calling "CrossMediaManager.Current.Stop();" in the onDestroy of the MainActivity keep somehow the app running somewhere.

**Comment by martijn00** [comment]
With this change: https://github.com/martijn00/XamarinMediaManager/commit/fc7f309ffa33bf3cf61fb3e4b56db914239c92a7#diff-744ab47974856b1e866d6b4a1c23f92fR80

You should be able to call stop and make the service stop. I am looking to see if i can pick up the destroy from within the service, but no luck there yet.

**Comment by martijn00** [comment]
Can you try with 0.7.0?

**Comment by valentin-debris** [comment]
@martijn00 , I'm not abble to compile. I added d8 but when a try to generate the solution, I have the error 

> Compilation can't be completed because some library classes are missing.	RadioPerfecto.Android	C:\Users\Valentin\Sites\RadioPerfectoApp\RadioPerfecto\RadioPerfecto.Android\R8

But I don't use R8, either  Proguard. 

Here is my config for Android
![image](https://user-images.githubusercontent.com/5438977/60610470-35023a00-9dc4-11e9-972d-9f74cb4f1457.png)

**Comment by martijn00** [comment]
@valentin-debris Yes you need to add d8, and then do a full clean build. Also you need to make sure to have the latest Visual Studio update, and have recent Android SDK installed.

**Comment by valentin-debris** [comment]
@martijn00 , still the same... I have VS 16.1.3 and the latest SDK.

**Comment by martijn00** [comment]
Can you post the full build output?

**Comment by valentin-debris** [comment]
I found this in the log "Missing class: org.apache.http.client.methods.HttpEntityEnclosingRequestBase" and somes issues on Google related to this (like https://github.com/xamarin/xamarin-android/issues/2670). 
I will try tomorrow with an empty project if it's related to a nugget or not.

**Comment by valentin-debris** [comment]
@martijn00 I was abble to compile with the fix explain in the link.
But the solution still doesn't work, when I kill the app, it's still there...

**Comment by martijn00** [comment]
0.7.2 should contain a fix for this. Can you test?

**Comment by valentin-debris** [comment]
@martijn00 just try it and the app is still running after closing it..
The only way for now I have found is using directly your source code and remove the NotificationListener from the PlayerNotificationManager by commented this line https://github.com/martijn00/XamarinMediaManager/blob/df4a6852e86017ddabd37226e7c9684aad36b7d0/MediaManager/Platforms/Android/MediaSession/MediaBrowserService.cs#L134

**Comment by martijn00** [comment]
Right, that means the PlayerNotificationManager probably needs to be destroyed from the service. I have a look at that for the next fix release.

**Comment by martijn00** [comment]
Can you test again with 0.7.3?

**Comment by valentin-debris** [comment]
@martijn00, nope, still the same. Also, I wasn't abble to find any new commit on github, is it normal ?

Thanks

**Comment by martijn00** [comment]
@valentin-debris I forgot to push, but here it is: https://github.com/martijn00/XamarinMediaManager/commit/2507ca7b0df6369e967086a4bab05bd5bec23fca#diff-744ab47974856b1e866d6b4a1c23f92fR163

**Comment by martijn00** [comment]
I've tested and it comes down to this line: https://github.com/martijn00/XamarinMediaManager/blob/develop/MediaManager/Platforms/Android/MediaSession/MediaBrowserService.cs#L121

When calling `StartForeground(notificationId, notification);` the service somehow keeps a foreground connection open and won't let the app die. I couldn't find out why yet, so any tips would be welcome.

**Comment by OdetteP** [comment]
@valentin-debris Did you solve this issue in the end?

**Comment by valentin-debris** [comment]
@OdetteP , I have to check with latest version but I think not, I have to kill to process in the onDestroy.

**Comment by OdetteP** [comment]
Did you read the last comment of Martijn? This is what he found. "When calling StartForeground(notificationId, notification); the service somehow keeps a foreground connection open and won't let the app die. I couldn't find out why yet, so any tips would be welcome".  Do you know why it keeps the foreground connection open?
