### ISSUE TITLE
Connectivity Issues (Android)

### ISSUE THREAD

**Issue by ivanrlg** [Baseflow/XamarinMediaManager#552]
## 🐛 Bug Report

Hello, I am new here, I am building a streaming app for a radio, where I am there are huge connectivity problems, and I have had several crashes when the internet fails, I tried the "Xamarin.Essentials: Connectivity" to stop streaming but It does not always detect that there is a connection failure. I report here because the appcenter throws me that the expectations are related to the MediaManager pluging, now I don't know if the problem is any configuration, bad programming on my part, or something else, that's why I would like you to help me.

### Expected behavior
That the application does not crash when it loses connectivity

### Reproduction steps
The application is running normally, but when it loses connectivity it crashes

### Configuration

**Version:** 0.7.7

**Platform:** 
- [ x] :robot: Android

Postscript: on some occasions the application stops playing in the background and automatically plays again when I enter it again. (I don't know if it is necessary to open another thread for this topic)

Attachment error log of the app center:

1) MediaExtractor.ExtractMetadata (MediaManager.Media.IMediaItem mediaItem)
C:\Users\mhvdi\Documents\OpenSource\XamarinMediaManager\MediaManager\Platforms\Android\Media\MediaExtractor.cs, line 32
Java.Lang.RuntimeException: setDataSource failed: status = 0x80000000

JniEnvironment+InstanceMethods.CallVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args)
JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters)
MediaMetadataRetriever.SetDataSource (System.String uri, System.Collections.Generic.IDictionary`2[TKey,TValue] headers)
MediaMetadataRetriever+<>c__DisplayClass138_0.<SetDataSourceAsync>b__0 ()
Task.InnerInvoke ()
Task.Execute ()

2) MediaItemExtensions.GetImageBitmapFromUrl (System.String url)
C:\Users\mhvdi\Documents\OpenSource\XamarinMediaManager\MediaManager\Platforms\Android\Media\MediaItemExtensions.cs, line 202
System.Net.WebException: The operation has timed out.

HttpWebRequest.RunWithTimeoutWorker[T] (System.Threading.Tasks.Task`1[TResult] workerTask, System.Int32 timeout, System.Action abort, System.Func`1[TResult] aborted, System.Threading.CancellationTokenSource cts)
HttpWebRequest.GetResponse ()
WebClient.GetWebResponse (System.Net.WebRequest request)
WebClient.DownloadBits (System.Net.WebRequest request, System.IO.Stream writeStream)
WebClient.DownloadDataInternal (System.Uri address, System.Net.WebRequest& request)
WebClient.DownloadData (System.Uri address)

3)MediaItemExtensions.GetImageBitmapFromUrl (System.String url)
C:\Users\mhvdi\Documents\OpenSource\XamarinMediaManager\MediaManager\Platforms\Android\Media\MediaItemExtensions.cs, line 201
System.Net.WebException: Error: NameResolutionFailure

WebConnection.Connect (System.Net.WebOperation operation, System.Threading.CancellationToken cancellationToken)
WebConnection.InitConnection (System.Net.WebOperation operation, System.Threading.CancellationToken cancellationToken)
WebOperation.Run ()
WebCompletionSource`1[T].WaitForCompletion ()
HttpWebRequest.RunWithTimeoutWorker[T] (System.Threading.Tasks.Task`1[TResult] workerTask, System.Int32 timeout, System.Action abort, System.Func`1[TResult] aborted, System.Threading.CancellationTokenSource cts)
HttpWebRequest.GetResponse ()

4) MediaItemExtensions.GetImageBitmapFromUrl (System.String url)
C:\Users\mhvdi\Documents\OpenSource\XamarinMediaManager\MediaManager\Platforms\Android\Media\MediaItemExtensions.cs, line 204
System.Net.WebException: Error getting response stream (ReadDoneAsync2): ReceiveFailure

WebResponseStream.InitReadAsync (System.Threading.CancellationToken cancellationToken)
WebOperation.Run ()
WebCompletionSource`1[T].WaitForCompletion ()
HttpWebRequest.RunWithTimeoutWorker[T] (System.Threading.Tasks.Task`1[TResult] workerTask, System.Int32 timeout, System.Action abort, System.Func`1[TResult] aborted, System.Threading.CancellationTokenSource cts)
HttpWebRequest.GetResponse ()
WebClient.GetWebResponse (System.Net.WebRequest request)
MediaItemExtensions.GetImageBitmapFromUrl (System.String url) C:\Users\mhvdi\Documents\OpenSource\XamarinMediaManager\MediaManager\Platforms\Android\Media\MediaItemExtensions.cs:204
MediaItemExtensions.GetCover (MediaManager.Library.IMediaItem mediaItem) C:\Users\mhvdi\Documents\OpenSource\XamarinMediaManager\MediaManager\Platforms\Android\Media\MediaItemExtensions.cs:189
MediaDescriptionAdapter.GetCurrentLargeIcon (Com.Google.Android.Exoplayer2.IPlayer player, Com.Google.Android.Exoplayer2.UI.PlayerNotificationManager+BitmapCallback callback) C:\Users\mhvdi\Documents\OpenSource\XamarinMediaManager\MediaManager\Platforms\Android\Media\MediaDescriptionAdapter.cs:41
PlayerNotificationManager+IMediaDescriptionAdapterInvoker.n_GetCurrentLargeIcon_Lcom_google_android_exoplayer2_Player_Lcom_google_android_exoplayer2_ui_PlayerNotificationManager_BitmapCallback_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_player, System.IntPtr native__callback)
(wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.122(intptr,intptr,intptr,intptr)

5) MediaItemExtensions.GetImageBitmapFromUrl (System.String url)
System.Net.WebException: The operation has timed out.

HttpWebRequest.RunWithTimeoutWorker[T] (System.Threading.Tasks.Task`1[TResult] workerTask, System.Int32 timeout, System.Action abort, System.Func`1[TResult] aborted, System.Threading.CancellationTokenSource cts)
HttpWebRequest.GetResponse ()
WebClient.GetWebResponse (System.Net.WebRequest request)
WebClient.DownloadBits (System.Net.WebRequest request, System.IO.Stream writeStream)
WebClient.DownloadDataInternal (System.Uri address, System.Net.WebRequest& request)
WebClient.DownloadData (System.Uri address)
MediaItemExtensions.GetImageBitmapFromUrl (System.String url)
MediaItemExtensions.GetCover (MediaManager.Media.IMediaItem mediaItem)
MediaDescriptionAdapter.GetCurrentLargeIcon (Com.Google.Android.Exoplayer2.IPlayer player, Com.Google.Android.Exoplayer2.UI.PlayerNotificationManager+BitmapCallback callback)
PlayerNotificationManager+IMediaDescriptionAdapterInvoker.n_GetCurrentLargeIcon_Lcom_google_android_exoplayer2_Player_Lcom_google_android_exoplayer2_ui_PlayerNotificationManager_BitmapCallback_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_player, System.IntPtr native__callback)
(wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.122(intptr,intptr,intptr,intptr)

**Comment by OdetteP** [comment]
Did you solve this issue?
