### ISSUE TITLE
To Know when the playlist finish

### ISSUE THREAD

**Issue by marcelovargas** [Baseflow/XamarinMediaManager#591]
## 🐛 Bug Report

This code  is not working, I don´t Know when finish the playlist
CrossMediaManager.Current.MediaQueue.QueueEnded += MediaQueue_QueueEnded;

### Expected behavior
I want to Know the when the list finish.

### Reproduction steps
I am using this code:
I need to update a playlist after finish and play again.

CrossMediaManager.Current.MediaQueue.QueueEnded += MediaQueue_QueueEnded;

private void MediaQueue_QueueEnded(object sender, MediaManager.Queue.QueueEndedEventArgs e)
{
Player();
}

    private async void Player()
    {
        await LoadList();

        if (playlist.Count != 0)
        {
            await CrossMediaManager.Current.Play(playlist);
        }

    }

### Configuration

Visual Studio 2019, Android 4.x,
**Version:** 1.x

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ x] :monkey: Xamarin.Forms

**Comment by marcelovargas** [comment]
Version plugin 0.8.5

**Comment by martijn00** [comment]
Try with 0.8.10

**Comment by OdetteP** [comment]
@marcelovargas Did you solve this issue with new version of the plugin?
