### ISSUE TITLE
iOS 13+ fullscreen (using ShowControls)

### ISSUE THREAD

**Issue by awatertrevi** [Baseflow/XamarinMediaManager#629]
## 🔙 Regression

The iOS VideoView no longer displays the video full screen when the fullscreen button is pressed.

### Old (and correct) behavior
The video opened in fullscreen and played without any issues (I've just tested this on iOS 12 and it still works).

### Current behavior
The video continues to play; however not in fullscreen. It's just an empty fullscreen view.

In the logging we find the following message:

`*** Warning: <MediaManager_Platforms_Ios_Video_PlayerViewController: 0x7f930c93de00> is trying to enter full screen, but is not in its view's window's view controller hierarchy. This results in undefined behavior.`.

### Reproduction steps
Sample repo can be found here: https://github.com/brminnick/AzureMediaServicesSampleApp (please do set ShowControls to true in the NativeVideoPlayerPage.cs file)
After clicking on the fullscreen button; you will see the following screen: 

![Simulator Screen Shot - iPhone 11 - 2019-10-12 at 15 20 53](https://user-images.githubusercontent.com/16825568/66702089-f3a6f200-ed03-11e9-805f-a543fa84dd5d.png)

### Configuration

**Version:** 0.8.12

**Platform:** 
- [x] :iphone: iOS 13
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
This works for me on the ElementPlayer.Forms.iOS sample project. What is different there?

**Comment by martijn00** [comment]
And on iOS 13.1?

**Comment by awatertrevi** [comment]
I've tested it on iOS 13.1 and iOS 13.2. Both don't work.

**Comment by martijn00** [comment]
I can't reproduce it. Please debug yourself and make a PR to help out.

**Comment by awatertrevi** [comment]
I managed to reproduce it in the ElementPlayer with the Apple 16*9 demo video (HLS). I shall try to fix it myself and create a pull request :)!

**Comment by OdetteP** [comment]
@awatertrevi did you manage to fix it?

**Comment by awatertrevi** [comment]
@OdetteP, I unfortunately did not manage to fix it. I shall try to upload a sample project tomorrow.

**Comment by awatertrevi** [comment]
[test.zip](https://github.com/Baseflow/XamarinMediaManager/files/3978430/test.zip)

Please find a sample Xamarin.Forms iOS project which reproduces the issue.

**Comment by ratka6** [comment]
This is a serious issue, can I get some guidance how to fix it myself for now?

**Comment by SatyaRamprasad** [comment]
@OdetteP @martijn00 Any update on this issue?

**Comment by ahmedsarfraz95** [comment]
Has anyone found a workaround for this to make it work until the problem is fixed?

The same problem while using:-
- Plugin.MediaManager **v0.9.7**
- iOS **v13.3.1**
- Xamarin Forms **v4.5.0.530**
- Prism.Forms **v7.2.0.1422**

**Comment by gabolarraguivel** [comment]
Same problem here! 
Still no workaround or solution to this issue.

**Comment by activa** [comment]
This issue is iOS 13 specific. It works fine on previous versions but fails on iOS 13.

**Comment by gabolarraguivel** [comment]
Is this project abandoned? Will this ever get fixed?

**Comment by martijn00** [comment]
Please make a PR

**Comment by sumathij** [comment]
I'm also facing the same issue

**Comment by kaviraj93** [comment]
Mid of October and still not fixed :(

**Comment by martijn00** [comment]
Mid of October and still no PR from you @kaviraj93

**Comment by irshadka** [comment]
Any update on this issue?

**Comment by emgapps** [comment]
This helped me:

`        protected override void DoViewDidLoad()
        {
            base.DoViewDidLoad();

            // Use manually created AVPlayerViewController for VideoView. FullScreen mode doesn't work properly with library implementation of ViewController
            ArticleVideoView.PlayerViewController = new AVPlayerViewController();
            AddChildViewController(ArticleVideoView.PlayerViewController);
        }
`

**Comment by nikhildpardasani** [comment]
Hi @emgapps, 
Can you please share the full platform specific code for this ?
And are you able to play this on iOS 14 ?
Any help would be appreciated. Thanks!

**Comment by emgapps** [comment]
> Hi @emgapps,
> Can you please share the full platform specific code for this ?
> And are you able to play this on iOS 14 ?
> Any help would be appreciated. Thanks!

That is all the code you actually need.
Forgot to mention that ArticleVideoView from my example is a VideoView property from IMediaManager.IMediaPlayer

For me it worked well on iOS 14.

**Comment by nikhildpardasani** [comment]
We do not have a Xamarin.iOS Project, but we have a Xamarin.Forms Project. Can you pease help in writing the code for this ?

**Comment by nikhildpardasani** [comment]
@martijn00, Can we get this bug solved soon? It is a small annoying issue
Any help would be appreciated. Thanks!

**Comment by martijn00** [comment]
Can you please make a PR?

**Comment by activa** [comment]
@martijn00 Based on your repeated (and rather arrogant) response asking people to fix it themselves, is it safe to assume that you have no desire to try and fix it? Since you started this project and have written most of the code, you have a lot more knowledge about this than people asking for a fix so it's normal that they're asking for a fix.

So, simple question: are you going to try and fix it or are you abandoning this project?

**Comment by martijn00** [comment]
@activa thanks for being arrogant yourself. Thinking you have any right to complain, any right to demand, any right to ask questions like that. You are actively being part of open source maintainer burnout. What have you done for open source? Have you paid any open source project or maintainer? Maybe go do some soul searching on how you can contribute being a nice addition to the open source community.

**Comment by jamsoft** [comment]
@martijn00 @emgapps  Hi All, Hi Martijn! Long time no speak! Hope you're well. Great library BTW, it's the only one we could get anywhere useful with! Nice one!

I've just run into this issue myself. It seems there is a solution detailed above but I'm on a Xam Forms app at the moment. What needs to go into this PR? Do we have an idea?

**Comment by martijn00** [comment]
Hey @jamsoft Long time ago! I suspect that the clues mentioned above are in the right direction. Somewhere the view doesn't get attached to the right ViewController in this specific case.

I would look into https://github.com/Baseflow/XamarinMediaManager/blob/develop/MediaManager/Platforms/Ios/Video/VideoView.cs#L35

It probably needs to search in the tree for the right ViewController or something.

**Comment by jamsoft** [comment]
Nice. I'll try to find some time over the weekend. This is the main issue I've encountered. The other was the MediaItemChanged event not firing on iOS but I worked around that, will try to look at that at the same time.

**Comment by Jearom** [comment]
Hi @martijn00 ,
 I do not know Xamarin.ios  but i think i make it work.  As far as i understand when player transition to full screen, player deleted inside "PlayerViewController" cause our xamarin forms page will dissapear.  So basically i just check if player going to full screen or leaving page and deleting Player conditionally to this. 

I Just change PlayerViewController like below. (Some one can make it better who knows xamarin ios :) )

Do you want me to make PR? 


```
public class PlayerViewController : AVPlayerViewController
    {
        public PlayerViewController()
        {
            this.AddObserver(this, "videoBounds", NSKeyValueObservingOptions.OldNew, Handle);
        }

        private bool savePlayer;


        protected static MediaManagerImplementation MediaManager => CrossMediaManager.Apple;

        public override void ViewWillAppear(bool animated)
        {
            base.ViewWillAppear(animated);

            if (MediaManager.MediaPlayer.AutoAttachVideoView && View.Superview is VideoView videoView)
                MediaManager.MediaPlayer.VideoView = videoView;
        }

        public override void ViewWillDisappear(bool animated)
        {
            base.ViewWillDisappear(animated);

            if (MediaManager.MediaPlayer.AutoAttachVideoView && MediaManager.MediaPlayer.VideoView == View.Superview)
            {
                MediaManager.MediaPlayer.VideoView = null;
            }

            if (!savePlayer)
                Player = null;

        }

        public override void ObserveValue(NSString keyPath, NSObject ofObject, NSDictionary change, IntPtr context)
        {
            if (keyPath == "videoBounds" && change != null && change[ChangeOldKey] != null)
            {
                var oldNsValue = change[ChangeOldKey];
                var newNsValue = change[ChangeNewKey];
                if (oldNsValue != null && newNsValue != null)
                {
                    var oldValue = (oldNsValue as NSValue).CGRectValue;
                    var newValue = (newNsValue as NSValue).CGRectValue;
                    if (oldValue != CGRect.Empty && oldValue != CGRect.Null && !oldValue.Equals(newValue))
                    {


                        if (UIScreen.MainScreen.Bounds.Height > UIScreen.MainScreen.Bounds.Width)
                        {
                            if (newValue.Y < oldValue.Y)
                            {
                                //normalScreen so you can empty the player 
                                savePlayer = false;
                            }
                            else
                            {
                                //fullScreen so you need to keep player.
                                savePlayer = true;
                            }
                        }
                        else
                        {
                            if (newValue.Height < UIKit.UIScreen.MainScreen.Bounds.Height)
                            {
                                savePlayer = false;
                            }
                            else
                            {
                                savePlayer = true;
                            }
                        }

                    }
                }
            }
        }
    }
```

**Comment by jamsoft** [comment]
@Jearom do you have this in a repository somewhere?

**Comment by Jearom** [comment]
> @Jearom do you have this in a repository somewhere?

sry, i  worked on my local but that was the only change i have made.

**Comment by jamsoft** [comment]
OK, I'm looking at this issue now and will check, test and build a PR.

**Comment by Jearom** [comment]
> OK, I'm looking at this issue now and will check, test and build a PR.

@jamsoft  I rechecked and i changed my observer to ;
this.AddObserver(this, "contentOverlayView.frame", NSKeyValueObservingOptions.OldNew, Handle);

this way much better and can handle videoGravity problems.

**Comment by jamsoft** [comment]
I must admit that today has been filled with getting my environment setup to compile this and I've been fighting with VS iOS bugs too.

It seems the sample iOS application in this repo immediately bombs when running it on my iPhone so was about to plug the DLLs straight into my solution for debugging and testing your solution.

A PR would be great if you can.

**Comment by jamsoft** [comment]
I'm just building a PR now.

**Comment by jamsoft** [comment]
Hmm, the code you've submitted isn't the same as the code detailed above.

**Comment by Jearom** [comment]
> Hmm, the code you've submitted isn't the same as the code detailed above.

Yes, as i said i change my observer to "contentOverlayView" so i could check parent view of the player is state of full screen or not. also i was checking the "Y" position of the player when portrait but now height  property better control for it.

**Comment by jamsoft** [comment]
@martijn00 Wow, thanks for the swift move on this one chap. Much appreciated.
