### ISSUE TITLE
MediaItemChanged not firing on url

### ISSUE THREAD

**Issue by Suplanus** [Baseflow/XamarinMediaManager#633]
## 🐛 Bug Report

I stream audio via url. If the title changed (in the webradio). The event is not firing.
Perhaps it is the same thing like #544 

### Expected behavior

Event should be fired.

### Reproduction steps

```csharp
CrossMediaManager.Current.MediaItemChanged += Current_MediaItemChanged;
var url = "http://www.rockantenne.de/webradio/channels/heavy-metal.aac.pls";
await CrossMediaManager.Current.Play(url);
```

### Configuration

**Version:** 0.8.18

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [x] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by Suplanus** [comment]
I also tested the MediaItem events:

```csharp
var mediaItem = await CrossMediaManager.Current.Play(url);
mediaItem.MetadataUpdated += MediaItem_MetadataUpdated;
mediaItem.PropertyChanged += MediaItem_PropertyChanged;
```

**Comment by Suplanus** [comment]
Also tested with:

```csharp
var mediaItem = await CrossMediaManager.Current.Extractor.CreateMediaItem(_url);
```

And also on iOS (added in description).

**Comment by Goldstrike** [comment]
Hi @Suplanus 
Any news about this? I encounter a similar issue with an url of a  webradio: no way to get automatically the metadata (title, artist, ...)

**Comment by Suplanus** [comment]
Which platform? Which streaming-url?

**Comment by Goldstrike** [comment]
I have a similar issue on iOS and Android.
The URL of the radio is: https://www.radioking.com/play/discothequefantastiqueradio

On iOS, I can recover the medata of the current item (title, artist,...) when I display the view. 
But I don't find a way to update the data automatically...

In add, on Android it's not possible at all.

**Comment by Suplanus** [comment]
iOS:  
I think you became the MetaDataChangedEvent one time...
Then you have to reset it:
`CrossMediaManager.Current.Queue.Current.IsMetadataExtracted = false;`

So you get it next time also.

Android:  
Sorry, streams don't work on my side because of #786

**Comment by Goldstrike** [comment]
Would you a sample to explain how you managed it?

In my case I register some events in the **ViewModel constructor**:

```
public RadioViewModel()
{            
    CrossMediaManager.Current.StateChanged += OnStateChanged;
    CrossMediaManager.Current.MediaItemFailed += OnCurrentMediaItemFailed;
    CrossMediaManager.Current.MediaItemChanged += OnCurrentMediaItemChanged;
}
```

Then I register the `MetadataUpdated` event after the call to `Play()`
```
IsBusy = true;
var mediaItem = await CrossMediaManager.Current.Play(radioUrl);
mediaItem.MetadataUpdated += MediaItem_MetadataUpdated;
```

I've did this in the `OnStateChanged` method:

```
private void OnStateChanged(object sender, MediaManager.Playback.StateChangedEventArgs e)
{
    //...
    CrossMediaManager.Current.Notification.UpdateNotification();
    CrossMediaManager.Current.Extractor.UpdateMediaItem(CrossMediaManager.Current.Queue.Current);
    CrossMediaManager.Current.Queue.Current.IsMetadataExtracted = false;
}
```

Like this, the native iOS player always recover correctly the current title/artist but I also would like to display these information in my app.

However the `OnCurrentMediaItemChanged` is only fired one time, and `MediaItem_MetadataUpdated` is never fired, so I don't see how I could recover these informations in the app...

On Android, I can play the audio stream without any problem, but I don't recover the metadata, neither in the app or in the native audio player...

**Comment by Suplanus** [comment]
Simple use the data of the player:

```csharp
ViewModel.Track = CrossMediaManager.Current.Queue.Current.Title;
ViewModel.Artist = CrossMediaManager.Current.Queue.Current.Artist;
```

**Comment by Goldstrike** [comment]
Hello @Suplanus , thanks for your help. I'm finally able to get the changes concerning the Metadata on iOS through the `MediaItem_PropertyChanged` event:

```
private void MediaItem_PropertyChanged(object sender, PropertyChangedEventArgs e)
{
    if (e.PropertyName == nameof(Source.Artist))
    {
        CurrentArtist = Source.Artist;
    }
    if (e.PropertyName == nameof(Source.Title))
    {
        CurrentTitle = Source.Title;
    }
}
```

On Android, the audio stream works fine from my side:

```
Source = await CrossMediaManager.Current.Play(radioUrl);
Source.MetadataUpdated += MediaItem_MetadataUpdated;
Source.PropertyChanged += MediaItem_PropertyChanged;
```

But I don't found any way to get the Metadata...

**Comment by Suplanus** [comment]
> Sorry, streams don't work on my side because of #786

If it works on your side but the event is not triggered you have to open a new issue.
