### ISSUE TITLE
Video is not loading.

### ISSUE THREAD

**Issue by Tazzad00** [Baseflow/XamarinMediaManager#639]
Hello good sir, and thanks for all the work you've done with this!

I am creating my app with xamarin.forms, but I am having an issue, and that is that the screen is black, but the video is not loading. (On android. I am not able to test on iOS.)
similar to this: https://github.com/BaseflowIT/XamarinMediaManager/issues/508.
I am very new to everything that has to do with creating an app, but I have followed everything in the readme file.
I am targeting 9.0, using d8, r8, and everything is up to date. I have also added all the permissions.

I would appreciate any reply. Thank you.

**Comment by OdetteP** [comment]
Can you please add some code to the sample project in github repro.
