### ISSUE TITLE
Videos are not playing in sequence

### ISSUE THREAD

**Issue by chinni-nag** [Baseflow/XamarinMediaManager#645]
## 🐛 Bug Report

Can you Please let me know How to play the video files in sequence  i am using Crossmanager.current.play(mediaitems); with this line videos are playing in not in sequence.

Videos should play in sequence

Try to pass list of items to the video player will get this bug.

**Platform:** 
Android.
Ios

**Comment by OdetteP** [comment]
Did you add your mediaItems to IEnumerable?  See link for more information
https://github.com/Baseflow/XamarinMediaManager/blob/54c29cd694d0c8a2585f0cfb61b2f2480f26df72/MediaManager/IMediaManager.cs#L74
