### ISSUE TITLE
Can't watch unsecured (http) video on iOS

### ISSUE THREAD

**Issue by peacefulvibes** [Baseflow/XamarinMediaManager#646]
Hi - I hate to ask this question but can't watch a video on iOS over http, as in the example in the readme.md file:

CrossMediaManager.Current.Play("http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4");

What am I missing?  I updated Info.plist with suggested values but didn't work (also tried NSAllowsArbitraryLoads)

	<key>NSAppTransportSecurity</key>
	<dict>
		<key> NSAllowsArbitraryLoadsInMedia</key>
		<true/>
	</dict>

Getting these errors:

Cannot start load of Task <4BA6D619-81C2-437C-ADA4-4A8BD752C2C7>.<2> since it does not conform to ATS policy

Task <4BA6D619-81C2-437C-ADA4-4A8BD752C2C7>.<2> finished with error [-1022] Error Domain=NSURLErrorDomain Code=-1022 "The resource could not be loaded because the App Transport Security policy requires the use of a secure connection." UserInfo={NSLocalizedDescription=The resource could not be loaded because the App Transport Security policy requires the use of a secure connection., NSErrorFailingURLStringKey=http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4, NSErrorFailingURLKey=http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <4BA6D619-81C2-437C-ADA4-4A8BD752C2C7>.<2>"
), _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <4BA6D619-81C2-437C-ADA4-4A8BD752C2C7>.<2>, NSUnderlyingError=0x6000034f3690 {Error Domain=kCFErrorDomainCFNetwork Code=-1022 "(null)"}}

Value cannot be null.
Parameter name: data

thanks,

**Comment by Suplanus** [comment]
Have you tested [this](https://stackoverflow.com/questions/31254725/transport-security-has-blocked-a-cleartext-http)?

```xml
<key>NSAppTransportSecurity</key>
<dict>
	<key>NSAllowsArbitraryLoads</key>
	<true/>
</dict>
```

**Comment by martijn00** [comment]
See the readme

**Comment by peacefulvibes** [comment]
I did see the readme as I said in my first sentence.  I am reluctant to use just NSAllowsArbitraryLoads because apple may reject app.  Anyway that and NSAllowsArbitraryLoadsForMedia works when I run on my iPhone but not on the simulator, seems to be an issue on simulator.  f so, would be good to make it clear on the readme so others dont run into same issue..  regards,
