### ISSUE TITLE
iOS notifications not working properly

### ISSUE THREAD

**Issue by rrispoli** [Baseflow/XamarinMediaManager#652]
## 🐛 Bug Report

The CrossMediaManager.Current.Notification.Enabled property setted to False is not working properly. The media notification with play/pause controls is always visible after play some media and the only way to disable it is close the app.

I tried call CrossMediaManager.Current.Notification.UpdateNotification() after set the Enabled property to false, but that didn't solve it either.

I've tested in iOS 12.4.4 in real device.

EDIT: In iOS 13.2.2 simulator the notifications are not showing properly, they just be visible in second media played, but the controls and seekbar are not updating. I think iOS 13 have more problems than just the Enabled property.

### Expected behavior

Enabled property setted to True: notification still visible.
Enabled property setted to False: dismiss the media notification.

Notification work properly in iOS 13.

### Reproduction steps

Set Notification.Enabled to True and Play some media, then change Notification.Enabled to False and play other media. The media notification will be visible in both.

### Configuration

**Version:** 0.9.1

**Platform:** 
- [x ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by rrispoli** [comment]
I've tested more in iOS 13.2.2 Simulator and notifications are not working properly, I edited the issue.

**Comment by rrispoli** [comment]
Hi @martijn00, did you get to reproduce this problem in iOS 13?

**Comment by Suplanus** [comment]
This is [fixed](https://github.com/Baseflow/XamarinMediaManager/pull/656) in the current NuGet.
