### ISSUE TITLE
disabeling notifications on android not working

### ISSUE THREAD

**Issue by steeephaaaaaaaan** [Baseflow/XamarinMediaManager#665]
## 🐛 Bug Report

The player-controls in the android Notification Center can not be hidden.
When I try to disable them like so:

    CrossMediaManager.Current.Notification.Enabled = false;

My code never returns from that line in debugger.

### Expected behavior
Controls in Notification Center will not show up 

### Configuration
set CrossMediaManager.Current.Notification.Enabled = false;

**Version:** 0.9.6

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by flpcarv** [comment]
@steeephaaaaaaaan 
I manged to workarround with this issue, it may be even be the right way to do it.

```
if (MainThread.IsMainThread)
{
	CrossMediaManager.Current.Notification.Enabled = false;
	await CrossMediaManager.Current.Play(MediaItem);
} else
{
	await MainThread.InvokeOnMainThreadAsync(async () => {
		CrossMediaManager.Current.Notification.Enabled = false;
		await CrossMediaManager.Current.Play(MediaItem);
	});
}
```

Hope this help someone.
