### ISSUE TITLE
App crashes when in background

### ISSUE THREAD

**Issue by Pujolsluis** [Baseflow/XamarinMediaManager#670]
## 🐛 Bug Report

App crashes when in the background.
### Expected behavior
Normal app behavior.

### Reproduction steps
App crashes when in the background with the following stacktrace:
https://gist.github.com/Pujolsluis/77c1cb2eb7fedafa2372e639816df7bb

### Configuration

**Version:** 1.x
v0.9.4

**Platform:** 
- [X] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [X] :monkey: Xamarin.Forms

**Comment by orzech85** [comment]
Stacktrace is pointing out your code: 
`AudioMapPageViewModel._mediaManager_StateChanged (System.Object sender, MediaManager.Playback.StateChangedEventArgs e)`
What is the exact exception?

**Comment by Pujolsluis** [comment]
Hey @orzech85 ,

The exception I'm getting is "SIGABRT: Object reference not set to an instance of an object"

Here is a snippet of what's in my code:
https://gist.github.com/Pujolsluis/a2ba45ddef71c0261ce4b1697a8b5745

It shouldn't be a problem with that code since I'm doing null checks before accessing the values, if you see the stack trace after mentioning that method it talks about MediaManagerBase🤔 so maybe it's something inside of those methods.

**Comment by orzech85** [comment]
Your code is calling eg. `AcrPageDialog.ShowLoading();` and `AcrPageDialog.HideLoading();`. Have you tried removeing it?
