### ISSUE TITLE
How to Update Handle Current Album Image?

### ISSUE THREAD

**Issue by flashomer** [Baseflow/XamarinMediaManager#671]
## 💬 Questions and Help

How to Update Handle Current Album Image?

 code:

```
var webImage = new Image { Source = ImageSource.FromUri(new Uri("https://secure.meetupstatic.com/photos/event/4/7/b/8/600_455178360.jpeg")) };
        
            CrossMediaManager.Current.Queue.Current.Title = "Changed Title";
            CrossMediaManager.Current.Queue.Current.Artist= "Changed Artist";
            CrossMediaManager.Current.Queue.Current.AlbumImage = webImage;
            CrossMediaManager.Current.Queue.Current.AlbumImageUri = "https://secure.meetupstatic.com/photos/event/4/7/b/8/600_455178360.jpeg";
            CrossMediaManager.Current.Queue.Current.DisplayImage = webImage;
            CrossMediaManager.Current.Queue.Current.DisplayImageUri = "https://secure.meetupstatic.com/photos/event/4/7/b/8/600_455178360.jpeg";
            CrossMediaManager.Current.Queue.Current.Image = webImage;
            CrossMediaManager.Current.Queue.Current.ImageUri = "https://secure.meetupstatic.com/photos/event/4/7/b/8/600_455178360.jpeg";

            CrossMediaManager.Current.Notification.UpdateNotification();

            Console.WriteLine("Changed");
```

There is no image in Android:
http://prntscr.com/qvlln8

Plugin.MediaManager: 0.9.6

**Comment by Suplanus** [comment]
I think you have to call this before set:

```csharp
CrossMediaManager.Current.Queue.Current.IsMetadataExtracted = false;
```

**Comment by flashomer** [comment]
I added the code but it still doesn't work the same.

**Comment by flashomer** [comment]
> I think you have to call this before set:
> 
> ```cs
> CrossMediaManager.Current.Queue.Current.IsMetadataExtracted = false;
> ```

I added the code but it still doesn't work the same.

**Comment by mixernet** [comment]
I solved it in Android:
CrossMediaManager.Current.Queue.Current.IsMetadataExtracted = false; must be on false and the name of the cover images must not have spaces (Example: PinkFloyd-WishYouWereHere.jpg).
It works for me, only for Android.

Example:

 CrossMediaManager.Current.Queue.Current.AlbumImageuri = "https://www.example.com/images/PinkFloyd-WishYouWereHere.jpg";
