### ISSUE TITLE
Video not displaying in Android .

### ISSUE THREAD

**Issue by Denaindra** [Baseflow/XamarinMediaManager#672]
## 🐛 Bug Report

Plugin install without any issue. But video not displaying in Android. And unable to fine any errors .

**Version:** latest version

**Platform:** 
  Xamarin.Forms Android

**Comment by quintonv** [comment]
I have the same issue. I added the Plugin, copied XAML from sample. Video plays but screen stays blank. I did the Init function and added MediaManager.Forms.dll and MediaManager.dll as references.
I think it might be that my app uses Shell.

**Comment by jennablackwell** [comment]
I am having this same issue on Android - and i am also using AppShell.
