### ISSUE TITLE
App is crashing

### ISSUE THREAD

**Issue by hyderabadi-coder** [Baseflow/XamarinMediaManager#678]
## 🐛 Bug Report

When you drag the position slider of a player fastly App is crashing some times

### Expected behavior

App should not be crashed 

### Reproduction steps

Try to drag the slider  fastly , will get the this issue
### Configuration

**Version:** 1.x

**Platform:** 
- [ ] :iphone: iOS - 10

-

**Comment by mphill** [comment]
I think PR https://github.com/Baseflow/XamarinMediaManager/pull/716 will fix this. 

If you can give a stack trace, I could verify if this will fix it.
