### ISSUE TITLE
CrossMediaManager.Current.Init(this); Fatal Error - No overload for method

### ISSUE THREAD

**Issue by Juan804041** [Baseflow/XamarinMediaManager#682]
### Old (and correct) behavior
when update on the last versión of xamarin 
### Reproduction steps
CrossMediaManager.Current.Init(this); don't exits the method on Android MainActivity
### Configuration

**Version:** 1.x

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by pasha-o** [comment]
same issue - i get System.NotImplementedException:** 'This functionality is not implemented in the portable version of this assembly. You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.'

**Comment by martijn00** [comment]
Target Android 10 and use AndroidX nuget packages

**Comment by shaks786** [comment]
> Target Android 10 and use AndroidX nuget packages

Which nuget packages are these?
