### ISSUE TITLE
UWP crashes during initialization

### ISSUE THREAD

**Issue by drewkeller** [Baseflow/XamarinMediaManager#683]
To get the ElementPlayer.Forms.UWP sample to work, I added the OS != Windows_NT condition below so net472 is used instead of netstandard. Which might not be the best fix, but otherwise, NETSTANDARD always seems to get defined, thus always returning null instead of creating the MediaManagerImplementation. (I removed the Apple targets and such because I don't have a way to build them.) 

This issue also appears to affect the 0.9.7 Nuget package.

(from MediaManager.Forms.csproj)
```
  <PropertyGroup Condition=" '$(TargetsToBuild)' == 'All' ">
    <TargetFrameworks Condition=" '$(OS)' != 'Windows_NT' ">netstandard2.0;monoandroid10.0</TargetFrameworks>
    <TargetFrameworks Condition=" '$(OS)' == 'Windows_NT' ">monoandroid10.0;uap10.0.18362;net472;$(TargetFrameworks)</TargetFrameworks>
  </PropertyGroup>
```

(from CrossMediaManager.cs)
```
        private static IMediaManager CreateMediaManager()
        {
#if NETSTANDARD
            return null;
#else
#pragma warning disable IDE0022 // Use expression body for methods
            return new MediaManagerImplementation();
#pragma warning restore IDE0022 // Use expression body for methods
#endif
        }
```

**Comment by martijn00** [comment]
You need to target UWP 10.0.18362 or higher. Also install the nuget package into your app project, not just the netstandard project.

Use the proper issue template next time!

**Comment by drewkeller** [comment]
Targeting Windows 1903 helped the sample project to work. Perhaps the project should be fixed on the repository before the ticket is closed.

My project using the Nuget package is able to build with any version of windows before 1903, but it has the undesired feature in that it crashes upon initialization of MediaManager. However, if I target Windows 1903, then building fails because of the following two errors: 

```
Could not copy the file "[...]\.nuget\packages\plugin.mediamanager.forms\0.9.7\lib\uap10.0.18362\MediaManager\MediaManager.xr.xml" because it was not found.
Could not copy the file "[...]\.nuget\packages\plugin.mediamanager.forms\0.9.7\lib\uap10.0.18362\MediaManager\Platforms\Uap\Video\VideoView.xaml" because it was not found.
``` 

Copying the desired files manually from the MediaManager project /bin/ folders (after building) resolved those issues, but wow, that is hacky, and certainly not the intended procedure for installing a Nuget package :/ . Again, perhaps this issue should be fixed in the Nuget package before closing this ticket.

[Note: I had previously come to the conclusion that the ...errr... "main" project mentioned by the exception message is really the "platform specific" project and not the .Core project (see definition of "core"). Also that since the missing reference is not the only reason for getting this exception message, it is a misleading error sometimes (well, every time in my case, because I already had it referenced, according to the ElementPlayer sample projects I was following).]

Cheers
