### ISSUE TITLE
Media Player is stopped when the app is Killed by user or sytem

### ISSUE THREAD

**Issue by RichardSV15** [Baseflow/XamarinMediaManager#685]
## 🐛 Bug Report

How can we make sure a background audio is not killed by the system OS on Android?

I am using Xamarin Forms and I'm not sure if i understand how it should be implemented but I can't seem to make the media player to persist on long background audios. They get killed by the android OS [Haven't tested on IOS].

mentioned and closed on #410  offers not help since the link provided is no longer active

also this piece of code seems to be deprecated for ExoPlayer:

`((MediaManagerImplementation)CrossMediaManager.Current).MediaSessionManager = new MediaSessionManager(Application.Context, typeof(ExoPlayerAudioService));
var exoPlayer = new ExoPlayerAudioImplementation(((MediaManagerImplementation)CrossMediaManager.Current).MediaSessionManager);
CrossMediaManager.Current.AudioPlayer = exoPlayer;`

### Expected behavior
Background audio should not be killed by sytem OS.

### Reproduction steps
Play a long (1 hour long) audio... Go home, out device to sleep... Audio continues to play in the background... After 20-30 minutes.... App's main process will be killed by the system and cut off audio.

### Configuration
Plugin.MediaManagerForms: 0.9.7

**Version:** 1.x

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by RichardSV15** [comment]
I don't have much but i can contribute $40 dollars to help resolve this problem...

**Comment by RichardSV15** [comment]
Maybe allowing us to control the Notification/Media Playback MediaBrowserService foreground service?

Using my own Android foreground service I am able to keep code running even when the app is killed (And even call CrossMediaManager.current.play("my_url") to play audio) . But no matter what the "MediaBrowserService" that MediaManager uses gets killed (music stops) when the app's main process is killed... Am I the only one experiencing this? 🤔 What am I doing wrong?

**Comment by EddieNoureddine** [comment]
Hi @RichardSV15  , 
did you find any solution ? 
it seems to me that the app gets killed on a randomly timed manner! 
it sometimes gets killed after 10 minutes , sometime after 20-30 minutes!

**Comment by RichardSV15** [comment]
@EddieNoureddine 
I have yet to find a solution but a workaround that i have not yet fully implemented is to use Settings Values to restart the media item to it's last position after the player is killed.


> Code Snippet

            CrossMediaManager.Current.StateChanged += (sender, e) => {
                try
                {
                    switch (e.State)
                    {
                        case MediaManager.Player.MediaPlayerState.Buffering:
                            Debug.WriteLine("Buffering...");
                            break;
                        case MediaManager.Player.MediaPlayerState.Playing:
                            Debug.WriteLine("playing...");
                            break;
                        case MediaManager.Player.MediaPlayerState.Stopped:
                            Debug.WriteLine("Stopped...");
                            //This line is executed after the app and player is killed... 
                            //you may use saved settings to play your media item again 
                            //and seek to the last postion`
                            break;
                    }
                } catch(Exception ex)
                {
                    HelperMethod.PrintOut(ex);
                }
            };


I have tested that you can get the media Player to play at this point but I do have some problems seeking to the previous position.  If you are able to get a working workaround I love it if you share it!.

The basis of this method is to use the "CrossMediaManager.Current.PositionChanged" to save the MediaItem's position to the app's settings and of course once the user plays a media item or list. Save that to the App's settings as well. Then monitor whether the user is in the App's foreground or not.  If the user is not using the App set a flag so that when the app is killed you restart it and if the user is the one that stops it then you don't restart it.  You are probably already thinking of the many problems with this approach but that's the only thing I can offer for now since we still haven't figured out why the player gets killed in the first place.

**Comment by EddieNoureddine** [comment]
Let's just go simple on this.

as the app dies or killed by the system, there would be no triggers for the events, hence the 
`CrossMediaManager.Current.StateChanged += (sender, e) => {...}`

will never be accessssed. 

To keep you posted , I added the following line to the manifest ,

`<uses-permission android:name="android.permission.WAKE_LOCK" />`

and it seems to be working for now , tested the app for almost an hour playing tracks from https resource, non stop.

On profiling the app i Noticed that the WAKE_Lock is triggered after some time 

`05-24 20:57:11.280 D/PowerManagerUtil( 3651): fileWriteString to /sys/power/wake_lock, LightsService `.

If you can try it on your end and let me know , I'd really appreaciate it.

**Comment by RichardSV15** [comment]
surprisingly  "CrossMediaManager.Current.StateChanged" does get accessed and can play a new instance, but I am also against this solution.

I use both mp3 resources and https mp3 urls to play my media items and I've always had the WAKE_LOCK Permission added to my App and the player is still being killed so I can't confirm this would fix the issue.  

Thank you jumping into this issue, for a moment i felt this was only on my end only and no one else was experiencing this problem.  Can you confirm the issue is completely resolved for you testing it with a 60+ min single audio that is stored in the device rather than http?

**Comment by EddieNoureddine** [comment]
will run it again , and keep you posted. in the mean time if you ever had this issue solved let me know please , as  i am not 100% sure this solution will resolve the issue.

**Comment by martijn00** [comment]
Should be better in 0.9.9 because of the updated exoplayer + fix https://github.com/Baseflow/XamarinMediaManager/commit/1c13770f6b64eb6892ea2e844b12e941a2d29ec9
