### ISSUE TITLE
No sound with latest MediaManager 0.9.7 and Xamarin.Forms: 4.5.0.495

### ISSUE THREAD

**Issue by DjeblounSidali** [Baseflow/XamarinMediaManager#688]
## 🐛 Bug Report
**1. Init CrossMediaManager on MainActivity**
`protected override void OnCreate(Bundle savedInstanceState)
        {
            TabLayoutResource = Resource.Layout.Tabbar;
            ToolbarResource = Resource.Layout.Toolbar;

            base.OnCreate(savedInstanceState);

            Xamarin.Essentials.Platform.Init(this, savedInstanceState);
            global::Xamarin.Forms.Forms.Init(this, savedInstanceState);

            CrossMediaManager.Current.Init(this);
            
            LoadApplication(new App());
        }`

**2. Click on button to Execute the play function to read a stream**
`   
var mediaItem = await CrossMediaManager.Current.Play("http://tasfiaradio.servemp3.com:8000/tasfia1");
`
Same with 
`
 IMediaItem mediaFile = await CrossMediaManager.Current.Extractor.CreateMediaItem("http://tasfiaradio.servemp3.com:8000/tasfia1");
 var mediaItem = await CrossMediaManager.Current.Play(mediaFile);
`
### Expected behavior
* hear sound

### Configuration
**Plugin.MediaManager:** 0.9.7
**Xamarin.Forms:** 4.5.0.495

**Platform:** 
- [ ] :monkey: Xamarin.Forms

**Comment by carlosanpardo** [comment]
Try using a https source like https://ia800806.us.archive.org/15/items/Mp3Playlist_555/AaronNeville-CrazyLove.mp3 if works you need cehck this issue:

https://github.com/Baseflow/XamarinMediaManager/issues/579
