### ISSUE TITLE
MediaItem duration

### ISSUE THREAD

**Issue by ShadowOfPhantom** [Baseflow/XamarinMediaManager#691]
## 💬 Questions and Help

Hi! I have two devices for tests, and the Plugin works differently on each one. My problem is Duration of a media items. One of my devices always show me default value of duration but other one show duration properly. Could you please tell me how this works? Where I possibly went wrong?

My code is something like this:

_audio = await CrossMediaManager.Current.Extractor.CreateMediaItem(pathWithFileName);

_audio.Duration // is default on my first device and shows correct value on my second one

P.S. metadata updated property does't solve the problem
Thank you in advance! :)

**Comment by RichardSV15** [comment]
I have experienced the same issue and haven't pin pointed what really causes it but it has to do with the values not yet being set in my experience... Try to do something like

await Task.Delay(600);

and see if you are able to get the duration after that.  In my experience I have to do this for IOS and it works without on Android.   Maybe I am also doing something wrong but I'm happy to help out and investigate further!

**Comment by ShadowOfPhantom** [comment]
> I have experienced the same issue and haven't pin pointed what really causes it but it has to do with the values not yet being set in my experience... Try to do something like
> 
> await Task.Delay(600);
> 
> and see if you are able to get the duration after that. In my experience I have to do this for IOS and it works without on Android. Maybe I am also doing something wrong but I'm happy to help out and investigate further!

Hi! Thank you for your comment, unfortunately it doesn't work for me :(

**Comment by RichardSV15** [comment]
Sorry to hear that. I also notice you are trying to get the duration before the "play" method... Try to get the duration after playing your media item. That's the what's different between your code and mine.

Maybe once you play the item, then that's when the duration is loaded into the duration variable

**Comment by ShadowOfPhantom** [comment]
> Sorry to hear that. I also notice you are trying to get the duration before the "play" method... Try to get the duration after playing your media item. That's what's different between your code and mine.
> 
> Maybe once you play the item, then that's when the duration is loaded into the duration variable

This doesn't works too. But I noticed an interesting thing that possibly is good to know: the files I can not get duration of can not be played by any default player on the device (I checked it by downloading them using default download manager). The file is ogg opus encoded so I can propose that this is an issue caused by unsupported by sysem format.

**Comment by ShadowOfPhantom** [comment]
> Sorry to hear that. I also notice you are trying to get the duration before the "play" method... Try to get the duration after playing your media item. That's what's different between your code and mine.
> 
> Maybe once you play the item, then that's when the duration is loaded into the duration variable

Yes, the device I have the problem with is on MIUI which don't support .ogg opus. It seems like that It is not the plugin issue.

**Comment by RichardSV15** [comment]
Completely agree with it possibly being a format Issue... Is your issue fixed when you use a different file format like mp3?

**Comment by ShadowOfPhantom** [comment]
> Completely agree with it possibly being a format Issue... Is your issue fixed when you use a different file format like mp3?

 I'm going to implement ogg-mp3 converter right now, I'll let you know when I check this out :)

**Comment by ShadowOfPhantom** [comment]
> Completely agree with it possibly being a format Issue... Is your issue fixed when you use a different file format like mp3?

Hi! I'm back to let you know that it works great with mp3. As I thought the problem is opus which MIUI doesn't support. I'll close the issue if you don't mind and maybe this will be helpful for anyone faced with the same problem! :)
