### ISSUE TITLE
Video don't start playing on iOS and Android Xamarin.Forms version : 4.5.0.530

### ISSUE THREAD

**Issue by marsel-mo** [Baseflow/XamarinMediaManager#692]
## 🐛 Bug Report

After install this nugets to all my projects in my solution :
```
Plugin.MediaManager (0.9.7)
Plugin.MediaManager.Forms (0.9.7)
```

 Initialise plugin: 
```
Android : CrossMediaManager.Current.Init(this);
iOS : CrossMediaManager.Current.Init();
```

Added to info.plist on iOS so i can use http://
```
<key>NSAppTransportSecurity</key>
<dict>
	<key>NSAllowsArbitraryLoadsInMedia</key>
	<true/>
</dict>
```

my xaml code is: 
```ruby
<ContentPage.Content>
        <StackLayout>
            <mm:VideoView
                BackgroundColor="Red"
                VerticalOptions="FillAndExpand"
                VideoAspect="AspectFit"
                ShowControls="True"
                Source="http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4"
                />
        </StackLayout>
    </ContentPage.Content>
```

### ******* I use navigation from Shell !!!!
I'm testing android - iOS on Emulator - Simulator. 
And i get this: 

No video is start playing just video view!

iOS: 

![Simulator Screen Shot - iPhone 11 - 2020-04-05 at 14 34 56](https://user-images.githubusercontent.com/40324065/78498828-fe8b8e00-774c-11ea-8af0-203d24c7f952.png)

Android: 

![Screenshot_1586090143](https://user-images.githubusercontent.com/40324065/78498838-13682180-774d-11ea-9120-20f77c470787.png)

Xamarin.Forms version : 4.5.0.530
No error. 

**Platform:** 
- [x] :robot: Android
- [x] :iphone: iOS

**Comment by InquisitorJax** [comment]
+1 on this guy. Just want to play a youtube link within the app, and it's coming up blank :(
If anyone has a work-around, it'd be much appreciated.

**Comment by marsel-mo** [comment]
@InquisitorJax  

Ok it's work with this link. 

https://archive.org/download/BigBuckBunny_328/BigBuckBunny_512kb.mp4 

But it's take a long time befor it's start to play and some time its reload the video and start play it from the start agen.

**Comment by AndreasReitberger** [comment]
@marsel-mo 
I ran into the same error and figured out it's related to the "https://"
I tried your video here: 
Doesn't work:
http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4

Works:
https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4

I guess it has something to do with this:

> If you are playing audio from a http resource you have to take care of ATS. Optionally you can disable this for playing media. Add the following to your info.plist:

**Comment by marsel-mo** [comment]
@AndreasReitberger 
Yes you are right, when I posted my comment with new link I didn’t described that the problem was in https.
Thanks for your comment hope it will help others to understand and solve this issue))))

**Comment by martijn00** [comment]
It has this information in the readme.
