### ISSUE TITLE
Not working on Xamarin.Forms Android and Sample Crashes on App Launch

### ISSUE THREAD

**Issue by jennablackwell** [Baseflow/XamarinMediaManager#693]
## 🐛 Bug Report

Following the given instructions does not seem to work.  Added Init() in the MainActivity, added the videoplayer to XAML and controls show but video never plays.  When I use other video players, the video plays.  

When trying to run the Xamarin Forms Android Sample Project - it deploys to device, then immediately crashes after the home screen loads.  When trying to run the other Android project (non forms) - it crashes too.

### Configuration

**Version:** 1.x

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Fixed
