### ISSUE TITLE
0.97 Lower Minimum Versions for NuGet Packages.

### ISSUE THREAD

**Issue by MichaelPeter** [Baseflow/XamarinMediaManager#695]
## 🏗 Enhancement Proposal

I Had a lot of issues with on 0.97: https://github.com/Baseflow/XamarinMediaManager/issues/443
that the implementations could not be loaded since I target
Android 9.0 and UWP Target Version 18362, Min Version 16299. 

Is it really nessary that the NuGet Package in the latest version requires Build 18362 and Android 10.0? I had to go back to 0.96 for the moment. Are there features used of these versions?

![image](https://user-images.githubusercontent.com/4217002/78513820-83f35a80-77ae-11ea-9c6b-c06405fd03d3.png)

### Pitch
Reduce the Mi

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [X] :robot: Android
- [ ] :checkered_flag: WPF
- [X] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by MichaelPeter** [comment]
Ok, figured a bit more out. With Android it is not really a issue, since only the compiling version is deciding not the minimum version.

But for UWP the deciding factor if the netstandard or the the UAP package is picked is the targetet MINIMUM version. So if I do not want to target the latest Windows Version and be able to install on windows pcs which don't have the latest version, I need to pick 0.96, since 0.97 does not allow to set minimum version to 10.0.1699.

If I set the Minimum Version to 10.0.18263 the uap package of 0.97 is picked

![image](https://user-images.githubusercontent.com/4217002/79081496-53676f80-7d1e-11ea-9cb5-9f48d6ce14c7.png)

**Comment by martijn00** [comment]
UWP is now set to 17763. Android needs 10 since we target AndroidX
