### ISSUE TITLE
NotImplementedException thrown in Mvx.IoCProvider.RegisterSingleton

### ISSUE THREAD

**Issue by hadihashem** [Baseflow/XamarinMediaManager#696]
### Old (and correct) behavior
Plateform projects run correctly

### Current behavior
System.NotImplementedException() thrown in : ElementPlayer.Core => App.cs => Initialize() => Mvx.IoCProvider.RegisterSingleton(CrossMediaManager.Current);

Full message: This functionality is not implemented in the portable version of this assembly. You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.

### Reproduction steps
Download the Samples
Open with visual studio
Run the related platform projects

### Configuration
x86, VS2017

**Version:** 1.x
WIN10 target v1903, .NET Standard 2.0, .NET Framework 4.6.1

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [x] :checkered_flag: WPF
- [x] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

Behavior not tested on the other platforms

**Comment by martijn00** [comment]
Set minimum uwp version higher.

**Comment by hadihashem** [comment]
Tested on all versions from Fall Creators Update to 1903
Same problem is always showing
