### ISSUE TITLE
java.lang.IllegalArgumentException: Description cannot be null

### ISSUE THREAD

**Issue by ShadowOfPhantom** [Baseflow/XamarinMediaManager#704]
Hi! I don't know if it is a bug, just my user reported that my app crashes. It looks like he is the only one who has faced with this. Could you please tell me where I'm wrong? Thanks in advance! :) That's all we know:

From Google Play console:

Galaxy S8 (dreamlte)
Samsung
CP: Samsung Exynos 8895
Platform armeabi-v7a, armeabi, arm64-v8a
RAM (MB) 4096
1080 × 2220, (DPI) 480 OpenGL ES 3.2ОС Android 9

And that's what App Center says:

android.support.v4.media.session.MediaSessionCompat$QueueItem.
MediaSessionCompat.java, line 1962
java.lang.IllegalArgumentException: Description cannot be null

android.support.v4.media.session.MediaSessionCompat$QueueItem. MediaSessionCompat.java:1962
android.support.v4.media.session.MediaSessionCompat$QueueItem. MediaSessionCompat.java:1954
com.google.android.exoplayer2.ext.mediasession.TimelineQueueNavigator.publishFloatingQueueWindow TimelineQueueNavigator.java:196
com.google.android.exoplayer2.ext.mediasession.TimelineQueueNavigator.onTimelineChanged TimelineQueueNavigator.java:108
com.google.android.exoplayer2.ext.mediasession.MediaSessionConnector$ExoPlayerEventListener.onTimelineChanged MediaSessionConnector.java:790
com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.notifyListeners ExoPlayerImpl.java:779
com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo ExoPlayerImpl.java:716
com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo ExoPlayerImpl.java:647
com.google.android.exoplayer2.ExoPlayerImpl.handleEvent ExoPlayerImpl.java:592
com.google.android.exoplayer2.ExoPlayerImpl$1.handleMessage ExoPlayerImpl.java:125
android.os.Handler.dispatchMessage Handler.java:106
android.os.Looper.loop Looper.java:214
android.app.ActivityThread.main ActivityThread.java:7050
java.lang.reflect.Method.invoke Method.java
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run RuntimeInit.java:494
com.android.internal.os.ZygoteInit.main ZygoteInit.java:965

**Comment by MrSerWin** [comment]
I have the same problem. And I can reproduce it easily 
https://github.com/Baseflow/XamarinMediaManager/issues/753

**Comment by Kienhht-Lotusapp** [comment]
Same issue,
It was reproducible on many phones.
Steps are: when video is playing, I turned off internet connection, then did seek the video, the video state was buffering then, and once it completed buffering, it crashed.
