### ISSUE TITLE
How do I update the value of MediaItem.DisplayTitle or DisplaySubtitle?

### ISSUE THREAD

**Issue by mixernet** [Baseflow/XamarinMediaManager#706]
Hello,
while the streaming stream (live radio and not mp3 file) is playing, how do I update the value of MediaItem.DisplayTitle or DispalySubtitle? Thanks a lot for the collaboration.

**Comment by milliamp** [comment]
I'm struggling with this at the moment too. The following works but it needs to be run from somewhere after the MediaExtractor has attempted to pull the metadata from the stream file.
I currently use this from the metadata updated event:
```                
CrossMediaManager.Current.Queue.Current.DisplayTitle = "New Title!";
CrossMediaManager.Current.Notification.UpdateNotification();
```

**Comment by milliamp** [comment]
I've found a better way now:
```
var mediaItem = await CrossMediaManager.Current.Extractor.CreateMediaItem(new FileInfo(sourceUrl));
mediaItem.DisplayTitle = "<title>";
mediaItem.DisplaySubtitle = "<subtitle>";
mediaItem.DisplayImageUri = "<imageurl>";

await CrossMediaManager.Current.Play(mediaItem);
```

**Comment by mixernet** [comment]
With an mp3 file there are no problems, the problem is on a streaming stream (e.g. live radio).
Try with this stream url:
"https://dreamsiteradiocp3.com:2199/rpc/radiocharlie/streaminfo.get"

**Comment by orassr** [comment]
@milliamp That might work with a file but not with a URL stream, 
`await CrossMediaManager.Current.Play(mediaItem.MediaUri);`
even when I use that I cannot get the stream going only when assign the url to a string.
