### ISSUE TITLE
DisplayImageUri not visible in control center (look-screen)

### ISSUE THREAD

**Issue by mixernet** [Baseflow/XamarinMediaManager#709]
Hi, I'm trying to develop an app for my radio. This is the code of the page for the play of the radio, everything works perfectly but the album covers are not displayed in the console center (look-screen) of the device, how come? Where's the mistake?
Thanks so much for your cooperation.

Code:

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xamarin.Forms;
using Xamarin.Forms.Xaml;
using MediaManager;
using System.Net.Http;
using System.IO;
using MediaManager.Library;
using MediaManager.Forms;
using MediaManager.Media;
using MediaManager.Playback;
using MediaManager.Player;
using System.Threading;
using System.Reflection;
using MediaManager.Notifications;
using MediaManager.Queue;
using MediaManager.Volume;
using MediaManager.Video;
using System.Xml;
using System.Xml.Linq;
using Newtonsoft.Json.Linq;

namespace XamarinLab
{
    [XamlCompilation(XamlCompilationOptions.Compile)]
    public partial class Radio : ContentPage
    {

        public Radio()
        {
            InitializeComponent();

            BtnStopClassic.IsVisible = false;

            _ = LeggiMetaData();

            Device.StartTimer(new TimeSpan(0, 0, 3), () =>
            {
                _ = LeggiMetaData();
                return true;
            });
        }

        public async Task LeggiMetaData()
        {
            var httpClient1 = new HttpClient();
            var ArtistaTitolo = await httpClient1.GetStringAsync("https://mysite.com/CoverAlbum/ArtistaTitolo.txt");
            var Artista = ArtistaTitolo.Substring(0, ArtistaTitolo.IndexOf('-'))?.Trim();
            var Titolo = ArtistaTitolo.Substring(ArtistaTitolo.IndexOf('-') + 1)?.Trim();

            var httpClient2 = new HttpClient();
            var ArtistaAlbum = await httpClient2.GetStringAsync("https://mysite.com/CoverAlbum/ArtistaAlbum.txt");

            TestDB.Text = Artista + " - " + Titolo;

            if (lblArtistaTitolo.Text != ArtistaTitolo)
            {
                //BackgroundImageSource = "https://mysite.com/CoverAlbum/" + ArtistaAlbum + ".jpg";

                imgCover.Source = new UriImageSource
                {
                    CachingEnabled = false,
                    Uri = new Uri("https://mysite.com/CoverAlbum/" + ArtistaAlbum + ".jpg")
                };
                lblArtistaTitolo.Text = ArtistaTitolo;                

                CrossMediaManager.Current.Queue.Current.DisplayTitle = Titolo;
                CrossMediaManager.Current.Queue.Current.DisplaySubtitle = Artista;
                CrossMediaManager.Current.Queue.Current.Album = "Radio Charlie Classic";
                CrossMediaManager.Current.Queue.Current.DisplayImageUri = "https://mysite/CoverAlbum/" + ArtistaAlbum + ".jpg";
                CrossMediaManager.Current.Notification.UpdateNotification();
            }
           
        }

        private void BtnPlayClassic_Clicked(object sender, EventArgs e)
        {
            BtnPlayClassic.IsVisible = false;
            BtnStopClassic.IsVisible = true;
            _ = PlayStreamingClassic();
        }

        public async Task PlayStreamingClassic()
        {
            var mediaItem = await CrossMediaManager.Current.Play("https://dreamsiteradiocp3.com/proxy/radiocharlie?mp=/stream");
        }

        private void BtnStopClassic_Clicked(object sender, EventArgs e)
        {
            BtnStopClassic.IsVisible = false;
            BtnPlayClassic.IsVisible = true;
            _ = StopStreamingClassic();
        }

        public async Task StopStreamingClassic()
        {
            await CrossMediaManager.Current.Stop();
        }
    }
}

**Comment by AleksandrAlekseev** [comment]
@mixernet Hi you find solution for problem?
I have too problem. 
I think using manually MPNowPlayingInfoCenter

**Comment by mixernet** [comment]
Hello @AleksandrAlekseev,
the code works quietly, you just have to rename the covers without spaces and without special characters, that's all.
To know before ...

**Comment by martijn00** [comment]
Fix in https://github.com/Baseflow/XamarinMediaManager/commit/58a98bee7a08aac0c4bb1ee5c3abe37a2d407fff

**Comment by adams-family** [comment]
It doesn't seem to work for me on version `1.0.8`:

mediaInfo.Queue.Current.AlbumImageUri = "https://icdn6.digitaltrends.com/image/smartphone-fm-radio-1500x1000.jpg";
mediaInfo.Queue.Current.DisplayImageUri = "https://icdn6.digitaltrends.com/image/smartphone-fm-radio-1500x1000.jpg";
mediaInfo.Queue.Current.ImageUri = "https://icdn6.digitaltrends.com/image/smartphone-fm-radio-1500x1000.jpg";
mediaInfo.Queue.Current.MediaUri = "https://icdn6.digitaltrends.com/image/smartphone-fm-radio-1500x1000.jpg";

Still my lock screen doesn't show the image :(

![IMG_F68E9B20F324-1](https://user-images.githubusercontent.com/19559733/107511971-782eac80-6ba6-11eb-9e88-f9bcf3cf54b8.jpeg)

What am I doing wrong?

**Comment by Goldstrike** [comment]
Hi @adams-family 
Do you found a solution? I encounter the same issue both on iOS and Android regarding the Album / Display image.

@mixernet 
Could you share a sample of URL that works for you?

**Comment by adams-family** [comment]
Hi @Goldstrike,

Yesterday I found a workaround by investigating the code inside of MediaManager. It works on iOS - however, I'm not satisfied with it and I think that it should be better addressed in the plugin. (I haven't tried Android yet)

This is my code:

```
CrossMediaManager.Current.Queue.Current.DisplayImageUri = url;     // any HTTPS JPEG
CrossMediaManager.Current.Queue.Current.IsMetadataExtracted = false;
CrossMediaManager.Current.Extractor.UpdateMediaItem(CrossMediaManager.Current.Queue.Current);
```

I can call this code at any time during playback.

Works on `1.0.8` but doesn't work on `0.8.0` so it has to be something relatively recent.

**Comment by Goldstrike** [comment]
@adams-family 
Your solution seems to work for me too on iOS, thank you!
Where do you call this code? I've call it in the `StateChanged` event, as the `MetadataUpdated` or `MediaItemChanged` events are not raised, but it's probably not the better way to achieve this...

There is no solution for Android?
I am also not able to display the Title/Artist on Android, whereas there is no problem on iOS...

**Comment by adams-family** [comment]
@Goldstrike 

I called it right before `CrossMediaManager.Current.Play(url)`.

I also tried calling it in a 'timer' during playback and it worked fine, artwork did change instantly. I only tested iOS so far.

**Comment by Goldstrike** [comment]
@adams-family 
I see, thank you.
And do you know if there is way to display a "local" image as `DisplayImage`?
I've did some tests, but it doesn't seem to work.

**Comment by adams-family** [comment]
@Goldstrike 

I think so, that works, as well, however… `DisplayImage` has to be castable to `UIImage` on iOS.

I was able to make it work, as well, however I had to:
  - create a DependencyService, for example:
      - an ImageConverter interface in the Forms project
      - an ImageConverterIOS class in the iOS project
      - a Convert method that converts your local image to UIImage
      - then call your your method from the Forms project as `DependencyService.Get<ImageConverter>().Convert(…)`

If you look into MediaManager's sources namely `NotificationManager.cs` you will get a better clue:

```
            var cover = mediaItem.DisplayImage as UIKit.UIImage;

            if (cover != null)
            {
                //TODO: Why is this deprecated?
                nowPlayingInfo.Artwork = new MPMediaItemArtwork(cover);
            }
```

Which is a very awkward workflow and I think that there is (or should be) a better way and I hope I am missing something.

**Comment by Goldstrike** [comment]
Thank you again @adams-family  
I've finally hosted the image I want to use, so I can display the expected image from an URL.
