### ISSUE TITLE
Videos are skipping when video id getting duplicate

### ISSUE THREAD

**Issue by chinni-nag** [Baseflow/XamarinMediaManager#710]
While passing list of videos to video player videos are skipping when videoid are same. 
for instance i am passing 4 videos and video ids  are 1,2,2,4 then video 1,2,4 are playing. video 2 is skipping.

### Expected behavior
Should play all in order even when video id are same like 1,2 ,2,4

### Reproduction steps
try to pass  duplicate video ids to video player.
### Configuration
visual studio 2019, Xamarin forms version -4.5.
media manger version-2.9.8

**Version:** 1.x

**Platform:** 
Ios, and Android both having same issue.

**Comment by Immons** [comment]
Why don't you assign correct IDs then?

**Comment by chinni-nag** [comment]
@Immons  As per requirement we need to handle even duplicate video id also.

**Comment by chinni-nag** [comment]
@Immons  Please let me know the issue any thing am missing here?
Thanks.
