### ISSUE TITLE
Play a video stream from an uri

### ISSUE THREAD

**Issue by AndreasReitberger** [Baseflow/XamarinMediaManager#715]
Hi,
I want to ask if there is a way to play a live stream (of a webcam for instance).
I have this uri 
"http://192.168.10.77/webcam/?action=stream"

For testing I implemented this videoview at my page.
```
<mm:VideoView VerticalOptions="FillAndExpand" 
                                                                  Source="http://192.168.10.77/webcam/?action=stream" 
                                                                  ShowControls="{Binding ShowControls}" 
                                                                  
                                                                  />
```

Sadly this seems not to work.

![image](https://user-images.githubusercontent.com/2952443/82728387-2ed4bf00-9cf0-11ea-9c49-a8396ce3f79b.png)

Then I tried it with the test uri (http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4)
But the result is the same. The player just tries to load it but no video is visible.

Thanks for helping out!

Edit:
Just figured out that the provided clip was not working because the simulator has issue with the ATS.
However the web stream still doesn't work. I set this in my info.plist.

```
<key>NSAppTransportSecurity</key>
  <dict>
    <key>NSAllowsArbitraryLoadsInMedia</key>
    <true/>
    <key>NSAllowsLocalNetworking</key>
    <true/>
  </dict>
```
Is there anything I miss?

**Comment by XonyON** [comment]
I think the issue in "http" protocol. Try to use "https".

**Comment by AndreasReitberger** [comment]
Hi, it‘s both not working. Either with http:// nor with https://

I rather think it‘s not working because of the local ip address..

Kind regards,
Andreas

**Comment by XonyON** [comment]
Yes, It could be true. If your device is not in the same network. You can try to test in mobile browser with the same URL

**Comment by AndreasReitberger** [comment]
> Yes, could be true. If your device is not in the same network. You can try to test in mobile browser with the same URL

Good idea, I‘ll try that.
Thanks!
