### ISSUE TITLE
MediaManager.Forms UWP: 'This functionality is not implemented in the portable version of this assembly.

### ISSUE THREAD

**Issue by AndyPresto** [Baseflow/XamarinMediaManager#717]
## 🐛 Bug Report

When I try to init CrossMediaManager from within a UWP project in Xamarin.Forms I get the below error.

`This functionality is not implemented in the portable version of this assembly. You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.`

My code in the UWP project looks like this.

```
namespace VideoPlayer.UWP
{
    public sealed partial class MainPage
    {
        public MainPage()
        {
            this.InitializeComponent();
            CrossMediaManager.Current.Init();
            LoadApplication(new VideoPlayer.App());
        }
    }
}
```

It works fine on Android but error's on UWP.

### Configuration
Xamarin.Forms 4.6
Plugin.MediaManager.Forms 0.97
.NET Standard 2.0
Building for Windows 10 17763

**Version:** 0.97

**Platform:** 
- [x] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Only beta 0.9.8 targets 17763. The current stable is one higher.

**Comment by Agredo** [comment]
I am getting the Same problem even after updating to 0.9.8 pre alpha 3.
Xamarin.Forms 4.7 
Building for Windows 10 17763 or Building for Windows 10 18362
