### ISSUE TITLE
Screen Black in Android 9

### ISSUE THREAD

**Issue by marcelovargas** [Baseflow/XamarinMediaManager#724]
## 🐛 Bug Report

the app shows a black screen when the player is playing the video without audio.

### Expected behavior

Show the video example (bunny.mp4)

### Reproduction steps

1. Use a device with the Android 9

### Configuration

- Visual Studio 2019 community
-  Nuget 0.8.7
Device with Android 9

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
I can't reproduce. Please add more info

**Comment by ligeirow** [comment]
i have the same problem... it dont work
