### ISSUE TITLE
[UWP] This functionality is not implemented in the portable version of this assembly

### ISSUE THREAD

**Issue by Agredo** [Baseflow/XamarinMediaManager#729]
## 🐛 Bug Report

From [#717](https://github.com/Baseflow/XamarinMediaManager/issues/717)

I am getting the Same problem even after updating to 0.9.8 pre alpha 3.
Xamarin.Forms 4.7
Building for Windows 10 17763 or Building for Windows 10 18362

Android and iOS are working

### Expected behavior

Working on UWP

### Reproduction steps

Use `CrossMediaManager.Current.Init(); ` in App.xaml.cs or MainPage.xaml.cs

### Configuration
Tested for 0.9.7 to 0.9.8 pre alpha 3.

**Platform:** 
- [OK] :iphone: iOS
- [OK] :robot: Android
- [ ] :checkered_flag: WPF
- [X] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [X] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
You have to set the minimum version to 17763 on 0.9.8-alpha3
