### ISSUE TITLE
[UWP] Exception when VideoView is inside a ScrollView

### ISSUE THREAD

**Issue by Agredo** [Baseflow/XamarinMediaManager#730]
[Sample.zip](https://github.com/Baseflow/XamarinMediaManager/files/4913126/Sample.zip)
## 🐛 Bug Report

Putting a VideoView into a ScrollView causes an exception. I attached a sample project  

### Expected behavior
No exception when a VideoView put into a ScrollView

### Reproduction steps
Put a ViewView into a ScrollView

### Configuration
Xamrin.Forms 4.7
Plugin.MediaManager.Fors 0.9.7-0.9.8 alpha 2 (tested) for UWP

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [X] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [X] :monkey: Xamarin.Forms

**Comment by Agredo** [comment]
I now had some time to investigate into this issue. The problem is in Namespace MediaManager.Forms.Platforms.Uap 
The class VideoViewRenderer overrides the method protected override Size MeasureOverride(Size availableSize)

availableSize.Width is 0 and availableSize.Height is infinity. The infinity causes this problem because 

_videoView.Height = availableSize.Height; 

does not work. I am not familiar overriding this method so I could not fix this immediately. Checking for !double.IsInfinity(availableSize.Height) is a fix for this but I dont think is the best way!

**Comment by martijn00** [comment]
Potential fix in https://github.com/Baseflow/XamarinMediaManager/commit/357299db82dba7ead9e7ede4b119149fa0c5512a
