### ISSUE TITLE
iOS: NotificationCenter live flag

### ISSUE THREAD

**Issue by Suplanus** [Baseflow/XamarinMediaManager#732]
## 🏗 Enhancement Proposal

If the source is a stream, in the NotificationCenter should be the live flag set: `MPNowPlayingInfoPropertyIsLiveStream`

### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Added in https://github.com/Baseflow/XamarinMediaManager/commit/004920cd41f42e5100b780a295508c5e76deb914

You need to set the property yourself at the moment. If you have a chance you can look into a PR to set this information from the system.
