### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by Inrego** [Baseflow/XamarinMediaManager#736]
I've forked the project, thinking I'd made some enhancements for pull requests.
The solution builds fine, but when launching any of the Android apps, the app completely freezes as soon as it tries to use any of the MediaManager api. I also tried to reference the projects from my own project/solution with same result.

**Comment by martijn00** [comment]
This is a problem because of the poor AndroidX support in Xamarin. I would love to get it working too.

**Comment by Inrego** [comment]
I didn't make any changes. The point is, just cloning this repo, I can't get the apps in the repo to work. I'd love some info on how to get it running so I can start making changes/fixes and make PR's.

**Comment by martijn00** [comment]
Yeah only the Android part freezes currently after some seconds. Try using iOS or any other platform to develop for now. Hopefully Microsoft will fix their issues some time.

**Comment by Inrego** [comment]
Which commit corresponds to v 0.9.7? I could fork from there to make my wanted changes.
I'm mostly finding bugs and issues on Android, so my PR's would mostly be on the Android side. So just doing it on iOS isn't really an option.
