### ISSUE TITLE
Is project dead again?

### ISSUE THREAD

**Issue by Inrego** [Baseflow/XamarinMediaManager#738]
No noteworthy updates for quite a while, and no answers to issues. Is this fantastic project dead agin? 😢

**Comment by martijn00** [comment]
It would be good to get support from the community or Microsoft. Currently it is stuck a bit because AndroidX support is poor in Xamarin.

**Comment by Inrego** [comment]
Can you elaborate on the AndroidX problems? Can you link to the last working commit? The commit that is corresponding nuget package version v0.9.7 - then I could fork from there.

**Comment by martijn00** [comment]
It started with this: https://github.com/Baseflow/XamarinMediaManager/commit/f4aa4e90bd8c0a924a317ab4fd92131be6a89261

But there is no way to go back, Exoplayer only supports AndroidX nodays.

Best would be if you investigate the problems and come up with a fix for the freezes. After that a new release is easy.

**Comment by Inrego** [comment]
idk, I'm using NuGet package 0.9.7 and it's working fine except for a few bugs. So I guess using an older exoplayer without androidX seems possible? Could just go that route until AndroidX issues are solved? or?

**Comment by Inrego** [comment]
But I'll try to look into solving the AndroidX issues. It's not my strong suite, but if it greases the wheels on this, it's worth the effort I think.

**Comment by martijn00** [comment]
Going with the older exoplayer doesn't work long term. That version is now already over a year old. If you get the problems fixed I would be happy to work on integrating new changes.

**Comment by Inrego** [comment]
I'm trying to look at it. Feels like trying to find a needle in a haystack. Do you have any findings to share, so I don't have to start from scratch?
I mean, AndroidX does work. Other libraries reference it, and I've also upgraded to AndroidX in my own app.

**Comment by Inrego** [comment]
I tried the commit you linked, but it doesn't compile. I wanted to try to go back then, and redo the upgrade to AndroidX. If you can provide me with a working solution folder/commit pre-androidX, I'd be happy to look at it.

**Comment by Inrego** [comment]
I just created a fresh new Android app, and added your newest version of the ExoPlayer NuGet (which references AndroidX), and used your sample code to play an audio file. It worked flawlessly. Are you sure AndroidX is the problem?

**Comment by Inrego** [comment]
Check this simple sample. It's playing the audio file just fine, using up-to-date ExoPlayer with AndroidX:
https://github.com/Inrego/ExoPlayerTest

**Comment by Inrego** [comment]
Been spending some hours. I have no experience with ExoPlayer whatsoever, so I'm starting completely from scratch, which makes it quite overwhelming.
I've created a new project (ExoPlayerTest linked above), which tries to replicate the basic principles of instantiating and using ExoPlayer. I've spent quite a bit of hours trying to find heads and tails of it all. No crashes like the one in your sample app. However, it's also still not playing anything (when using the same methods as XamarinMediaManager). Take a look and see what I'm missing: https://github.com/Inrego/ExoPlayerTest/tree/experiementation
I'm thinking if we can get ExoPlayer working in a simplified and isolated project, it could help pinpoint the issue in XamarinMediaManager.

**Comment by martijn00** [comment]
@Inrego I think that MvvmCross might have something to do with it. I want to remove it from the sample sometime and just use vanilla Xamarin. Maybe related to what is said here: https://github.com/Baseflow/ExoPlayerXamarin/issues/103#issuecomment-666261267

**Comment by Inrego** [comment]
I'm not sure if that's it, as I tried referencing it from my own project, which also caused crash. But I'll try to use a vanilla project, and see if it's bearing any fruit.

**Comment by Inrego** [comment]
Okay, I think maybe I'm getting closer. I copied all code (that isn't platform specific) from MediaManager to a seperate project, and all android specific code in a separate android library project. It required a little bit of refactoring, but nothing too big.
Now, I'm using this project in my small sample/test app, and this is the exception I'm getting:

    Could not load type 'Com.Google.Android.Exoplayer2.UI.PlayerNotificationManager.IMediaDescriptionAdapter' from assembly 'ExoPlayer.UI, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.

I tried downgrading the ExoPlayer NuGets to 2.11.4, and uncommented the two functions in MediaDescriptionAdapter, which was needed by this version. But now I'm getting:

    VTable setup of type MediaManager.Platforms.Android.Media.MediaDescriptionAdapter failed

Which coincidentally is the same class. If you have any input on this, that'd be great. I'll continue trying to solve it.

**Comment by martijn00** [comment]
@Inrego seems to be related to https://github.com/Baseflow/ExoPlayerXamarin/issues/108#issuecomment-670727866

I'm going to try and recompile with the latest. Would be great if you can test again after that.

**Comment by Inrego** [comment]
Great, let me know. It'll be an updated ExoPlayer package right?

**Comment by martijn00** [comment]
@Inrego the updated exoplayer is online. I'll push the update to MediaManager too

**Comment by Inrego** [comment]
The new version has some breaking changes for current MediaManager version. So some edits are indeed needed. When do you think the updated MediaManager will be ready? I don't have time to make any other changes except just testing updates right now.

**Comment by martijn00** [comment]
@Inrego it seems there was a problem with 2.11.7, i'm pushing a new one now. That should break less.

**Comment by Inrego** [comment]
Looks better - now playback actually started! However, the app crashed shortly after with the following:

> 08-10 12:32:53.365 I/MonoDroid(14878): UNHANDLED EXCEPTION:
> 08-10 12:32:53.376 I/MonoDroid(14878): Java.Lang.AbstractMethodError: abstract method "void com.google.android.exoplayer2.Player$EventListener.onTimelineChanged(com.google.android.exoplayer2.Timeline, int)"
> 08-10 12:32:53.377 I/MonoDroid(14878):   at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0008e] in <bf671abdfa384ce99d758b134b9dd5bf>:0 
> 08-10 12:32:53.377 I/MonoDroid(14878):   at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0005d] in <bf671abdfa384ce99d758b134b9dd5bf>:0 
> 08-10 12:32:53.377 I/MonoDroid(14878):   at Com.Google.Android.Exoplayer2.IPlayerEventListener.OnTimelineChanged (Com.Google.Android.Exoplayer2.Timeline timeline, System.Int32 reason) [0x0003a] in C:\Users\mhvdi\Documents\OpenSource\ExoPlayerXamarin\ExoPlayer.Core\obj\Release\monoandroid10.0\generated\src\Com.Google.Android.Exoplayer2.IPlayer.cs:1012 
> 08-10 12:32:53.377 I/MonoDroid(14878):   at Com.Google.Android.Exoplayer2.IPlayerEventListener.n_OnTimelineChanged_Lcom_google_android_exoplayer2_Timeline_I (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_timeline, System.Int32 reason) [0x00011] in C:\Users\mhvdi\Documents\OpenSource\ExoPlayerXamarin\ExoPlayer.Core\obj\Release\monoandroid10.0\generated\src\Com.Google.Android.Exoplayer2.IPlayer.cs:999 
> 08-10 12:32:53.377 I/MonoDroid(14878):   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.96(intptr,intptr,intptr,int)
> 08-10 12:32:53.377 I/MonoDroid(14878):   --- End of managed Java.Lang.AbstractMethodError stack trace ---
> 08-10 12:32:53.377 I/MonoDroid(14878): java.lang.AbstractMethodError: abstract method "void com.google.android.exoplayer2.Player$EventListener.onTimelineChanged(com.google.android.exoplayer2.Timeline, int)"
> 08-10 12:32:53.377 I/MonoDroid(14878): 	at crc64c8bbe22b5a883ae7.PlayerEventListener.n_onTimelineChanged(Native Method)
> 08-10 12:32:53.377 I/MonoDroid(14878): 	at crc64c8bbe22b5a883ae7.PlayerEventListener.onTimelineChanged(PlayerEventListener.java:121)
> 08-10 12:32:53.377 I/MonoDroid(14878): 	at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.lambda$run$0$ExoPlayerImpl$PlaybackInfoUpdate(ExoPlayerImpl.java:804)
> 08-10 12:32:53.377 I/MonoDroid(14878): 	at com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$PlaybackInfoUpdate$N_S5kRfhaRTAkH28P5luFgKnFjQ.invokeListener(Unknown Source:2)
> 08-10 12:32:53.377 I/MonoDroid(14878): 	at com.google.android.exoplayer2.BasePlayer$ListenerHolder.invoke(BasePlayer.java:182)
> 08-10 12:32:53.377 I/MonoDroid(14878): 	at com.google.android.exoplayer2.ExoPlayerImpl.invokeAll(ExoPlayerImpl.java:845)
> 08-10 12:32:53.377 I/MonoDroid(14878): 	at com.google.android.exoplayer2.ExoPlayerImpl.access$000(ExoPlayerImpl.java:43)
> 08-10 12:32:53.377 I/MonoDroid(14878): 	at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.run(ExoPlayerImpl.java:802)
> 08-10 12:32:53.377 I/MonoDroid(14878): 	at com.google.android.exoplayer2.ExoPlayerImpl.notifyListeners(ExoPlayerImpl.java:736)
> 08-10 12:32:53.377 I/MonoDroid(14878): 	at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:710)
> 08-10 12:32:53.377 I/MonoDroid(14878): 	at com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo(ExoPlayerImpl.java:652)
> 08-10 12:32:53.377 I/MonoDroid(14878): 	at com.google.android.exoplayer2.ExoPlayerImpl.handleEvent(ExoPlayerImpl.java:595)
> 08-10 12:32:53.377 I/MonoDroid(14878): 	at com.google.android.exoplayer2.ExoPlayerImpl$1.handleMessage(ExoPlayerImpl.java:127)
> 08-10 12:32:53.377 I/MonoDroid(14878): 	at android.os.Handler.dispatchMessage(Handler.java:106)
> 08-10 12:32:53.377 I/MonoDroid(14878): 	at android.os.Looper.loop(Looper.java:193)
> 08-10 12:32:53.377 I/MonoDroid(14878): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
> 08-10 12:32:53.377 I/MonoDroid(14878): 	at java.lang.reflect.Method.invoke(Native Method)
> 08-10 12:32:53.377 I/MonoDroid(14878): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
> 08-10 12:32:53.377 I/MonoDroid(14878): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by Inrego** [comment]
Here's my repro project:
https://github.com/Inrego/ExoPlayerTest/tree/experiementation

This is the one where I copied all relevant code to an android-only solution. Maybe it can be helpful for you.

**Comment by martijn00** [comment]
It's a bit much code to look at right now. I've pushed the update to develop. I can release a new nuget if you can confirm it works

**Comment by Inrego** [comment]
Alright, I'll test it later.
I'm curious, what's the reason for having all platforms in a single project with conditional compiling, rather than just shared code, and one project per target?
I've found that multi-targetting you're doing, is making it a bit hard to debug. For example, in latest version of develop, the UWP parts doesn't compile, which means I can't run the Android app, because the MediaManager project can't compile.
So I have to go and remove uap from the csproj to allow it to compile so I can test Android.

Besides, the conditional compiling doesn't work with new Xamarin project types (in case you decide to make a new sample app without MvvmCross).

**Comment by Inrego** [comment]
Just tried your sample app as well, and the same issue:

> 08-10 14:36:07.799 I/MonoDroid(15517): UNHANDLED EXCEPTION:
> 08-10 14:36:07.810 I/MonoDroid(15517): Java.Lang.AbstractMethodError: abstract method "void com.google.android.exoplayer2.ui.PlayerNotificationManager$NotificationListener.onNotificationPosted(int, android.app.Notification, boolean)"
> 08-10 14:36:07.810 I/MonoDroid(15517):   at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0008e] in <bf671abdfa384ce99d758b134b9dd5bf>:0 
> 08-10 14:36:07.810 I/MonoDroid(15517):   at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0005d] in <bf671abdfa384ce99d758b134b9dd5bf>:0 
> 08-10 14:36:07.810 I/MonoDroid(15517):   at Com.Google.Android.Exoplayer2.UI.PlayerNotificationManager+INotificationListener.OnNotificationPosted (System.Int32 notificationId, Android.App.Notification notification, System.Boolean ongoing) [0x00050] in C:\Users\mhvdi\Documents\OpenSource\ExoPlayerXamarin\ExoPlayer.UI\obj\Release\monoandroid10.0\generated\src\Com.Google.Android.Exoplayer2.UI.PlayerNotificationManager.cs:552 
> 08-10 14:36:07.810 I/MonoDroid(15517):   at Com.Google.Android.Exoplayer2.UI.PlayerNotificationManager+INotificationListener.n_OnNotificationPosted_ILandroid_app_Notification_Z (System.IntPtr jnienv, System.IntPtr native__this, System.Int32 notificationId, System.IntPtr native_notification, System.Boolean ongoing) [0x00011] in C:\Users\mhvdi\Documents\OpenSource\ExoPlayerXamarin\ExoPlayer.UI\obj\Release\monoandroid10.0\generated\src\Com.Google.Android.Exoplayer2.UI.PlayerNotificationManager.cs:538 
> 08-10 14:36:07.810 I/MonoDroid(15517):   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.89(intptr,intptr,int,intptr,bool)
> 08-10 14:36:07.810 I/MonoDroid(15517):   --- End of managed Java.Lang.AbstractMethodError stack trace ---
> 08-10 14:36:07.810 I/MonoDroid(15517): java.lang.AbstractMethodError: abstract method "void com.google.android.exoplayer2.ui.PlayerNotificationManager$NotificationListener.onNotificationPosted(int, android.app.Notification, boolean)"
> 08-10 14:36:07.810 I/MonoDroid(15517): 	at crc646e364d2ff34954e7.NotificationListener.n_onNotificationPosted(Native Method)
> 08-10 14:36:07.810 I/MonoDroid(15517): 	at crc646e364d2ff34954e7.NotificationListener.onNotificationPosted(NotificationListener.java:40)
> 08-10 14:36:07.810 I/MonoDroid(15517): 	at com.google.android.exoplayer2.ui.PlayerNotificationManager.startOrUpdateNotification(PlayerNotificationManager.java:1005)
> 08-10 14:36:07.810 I/MonoDroid(15517): 	at com.google.android.exoplayer2.ui.PlayerNotificationManager.handleMessage(PlayerNotificationManager.java:1307)
> 08-10 14:36:07.810 I/MonoDroid(15517): 	at com.google.android.exoplayer2.ui.PlayerNotificationManager.lambda$new$0$PlayerNotificationManager(PlayerNotificationManager.java:624)
> 08-10 14:36:07.810 I/MonoDroid(15517): 	at com.google.android.exoplayer2.ui.-$$Lambda$PlayerNotificationManager$S3i9ukqX74X9NHVfovI_cIquQsY.handleMessage(Unknown Source:2)
> 08-10 14:36:07.810 I/MonoDroid(15517): 	at android.os.Handler.dispatchMessage(Handler.java:102)
> 08-10 14:36:07.810 I/MonoDroid(15517): 	at android.os.Looper.loop(Looper.java:193)
> 08-10 14:36:07.810 I/MonoDroid(15517): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
> 08-10 14:36:07.810 I/MonoDroid(15517): 	at java.lang.reflect.Method.invoke(Native Method)
> 08-10 14:36:07.810 I/MonoDroid(15517): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
> 08-10 14:36:07.810 I/MonoDroid(15517): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by Inrego** [comment]
Looks like `PlayerNotificationManager.INotificationListener` doesn't have any members that need to be implemented? Removing everything from `MediaManager.Platforms.Android.MediaSession.NotificationListener` doesn't generate any compile-time errors. Is the interface generated correctly?

**Comment by martijn00** [comment]
Hmm, not sure. I use the experimental property to generate those default interfaces, because otherwise it is even more trouble. See https://github.com/Baseflow/ExoPlayerXamarin/blob/develop/Directory.build.props#L29

The c#8 default interfaces are still relatively new.

**Comment by Inrego** [comment]
I've found the solution. There are a few other exceptions due to interface method signatures having changed. I'll fix them and make a PR later today.

**Comment by Inrego** [comment]
by the way, the C#8 default interfaces are pretty annoying. It's much harder to figure out which methods you have to implement, since there are no errors for missing implementations. Same goes when a method signature has changed, no compilation exception, just at runtime.

**Comment by martijn00** [comment]
Thanks a lot! I'll have a look at testing it tomorrow.

**Comment by Inrego** [comment]
@martijn00  Would you be open to/interested in a PR that moves platform-specific code into separate projects, rather than a single project?

**Comment by martijn00** [comment]
@Inrego no it's not a good idea to split it up like that. How it is now is the way to go. Also when moving into the net5 projects coming november this is by far the best structure. Projects that split it up are going to be in trouble. More interesting is why UWP doesn't work for you, and how we can fix all the samples. Can you make a new issue for these things so we can discuss it there? Otherwise this issue gets too big and bloated with comments

**Comment by AswinPG** [comment]
This thread has helped me run the project just now. Thanks for all your work.
