### ISSUE TITLE
UWP can't compile

### ISSUE THREAD

**Issue by Inrego** [Baseflow/XamarinMediaManager#740]
I get many compiler errors on the UWP part of the MediaManager project:

> 1>------ Build started: Project: MediaManager, Configuration: Debug Any CPU ------
> 1>Inrego\XamarinMediaManager\MediaManager\Platforms\Uap\MediaManagerImplementation.cs(10,15,10,20): error CS0234: The type or namespace name 'Media' does not exist in the namespace 'Windows' (are you missing an assembly reference?)
> 1>Inrego\XamarinMediaManager\MediaManager\Platforms\Uap\MediaManagerImplementation.cs(11,15,11,21): error CS0234: The type or namespace name 'System' does not exist in the namespace 'Windows' (are you missing an assembly reference?)
> 1>Inrego\XamarinMediaManager\MediaManager\Platforms\Uap\Media\MediaItemExtensions.cs(5,15,5,20): error CS0234: The type or namespace name 'Media' does not exist in the namespace 'Windows' (are you missing an assembly reference?)
> 1>Inrego\XamarinMediaManager\MediaManager\Platforms\Uap\Media\MediaItemExtensions.cs(6,15,6,20): error CS0234: The type or namespace name 'Media' does not exist in the namespace 'Windows' (are you missing an assembly reference?)
> 1>Inrego\XamarinMediaManager\MediaManager\Platforms\Uap\Media\MediaItemExtensions.cs(7,15,7,22): error CS0234: The type or namespace name 'Storage' does not exist in the namespace 'Windows' (are you missing an assembly reference?)
> 1>Inrego\XamarinMediaManager\MediaManager\Platforms\Uap\Media\StorageFileProvider.cs(5,15,5,20): error CS0234: The type or namespace name 'Media' does not exist in the namespace 'Windows' (are you missing an assembly reference?)
> 1>Inrego\XamarinMediaManager\MediaManager\Platforms\Uap\Media\StorageFileProvider.cs(6,15,6,22): error CS0234: The type or namespace name 'Storage' does not exist in the namespace 'Windows' (are you missing an assembly reference?)
> 1>Inrego\XamarinMediaManager\MediaManager\Platforms\Uap\Media\StorageFileProvider.cs(7,15,7,22): error CS0234: The type or namespace name 'Storage' does not exist in the namespace 'Windows' (are you missing an assembly reference?)
> 1>Inrego\XamarinMediaManager\MediaManager\Platforms\Uap\Media\StorageFileProvider.cs(8,15,8,22): error CS0234: The type or namespace name 'Storage' does not exist in the namespace 'Windows' (are you missing an assembly reference?)
> 1>Inrego\XamarinMediaManager\MediaManager\Platforms\Uap\Media\StorageFileProvider.cs(9,18,9,22): error CS0234: The type or namespace name 'Core' does not exist in the namespace 'Windows.UI' (are you missing an assembly reference?)
> 1>Inrego\XamarinMediaManager\MediaManager\Platforms\Uap\Media\StorageFileProvider.cs(11,29,11,36): error CS0234: The type or namespace name 'Imaging' does not exist in the namespace 'Windows.UI.Xaml.Media' (are you missing an assembly reference?)
> 1>Inrego\XamarinMediaManager\MediaManager\Platforms\Uap\Player\PlaybackStateExtensions.cs(1,15,1,20): error CS0234: The type or namespace name 'Media' does not exist in the namespace 'Windows' (are you missing an assembly reference?)
> 1>Inrego\XamarinMediaManager\MediaManager\Platforms\Uap\Player\WindowsMediaPlayer.cs(9,15,9,20): error CS0234: The type or namespace name 'Media' does not exist in the namespace 'Windows' (are you missing an assembly reference?)
> 1>Inrego\XamarinMediaManager\MediaManager\Platforms\Uap\Volume\VolumeManager.cs(2,15,2,20): error CS0234: The type or namespace name 'Media' does not exist in the namespace 'Windows' (are you missing an assembly reference?)
> 1>Inrego\XamarinMediaManager\MediaManager\Platforms\Uap\MediaManagerImplementation.cs(15,79,15,90): error CS0246: The type or namespace name 'MediaPlayer' could not be found (are you missing a using directive or an assembly reference?)
> 1>Inrego\XamarinMediaManager\MediaManager\Platforms\Uap\Media\MediaItemExtensions.cs(13,34,13,45): error CS0246: The type or namespace name 'MediaSource' could not be found (are you missing a using directive or an assembly reference?)
> 1>Inrego\XamarinMediaManager\MediaManager\Platforms\Uap\Media\MediaItemExtensions.cs(25,66,25,77): error CS0246: The type or namespace name 'MediaSource' could not be found (are you missing a using directive or an assembly reference?)
> 1>Inrego\XamarinMediaManager\MediaManager\Platforms\Uap\Media\MediaItemExtensions.cs(25,23,25,40): error CS0246: The type or namespace name 'MediaPlaybackItem' could not be found (are you missing a using directive or an assembly reference?)
> 1>Inrego\XamarinMediaManager\MediaManager\Platforms\Uap\Player\PlaybackStateExtensions.cs(8,64,8,82): error CS0246: The type or namespace name 'MediaPlaybackState' could not be found (are you missing a using directive or an assembly reference?)
> 1>Inrego\XamarinMediaManager\MediaManager\Platforms\Uap\Media\MediaItemExtensions.cs(30,66,30,77): error CS0246: The type or namespace name 'MediaSource' could not be found (are you missing a using directive or an assembly reference?)
> 1>Inrego\XamarinMediaManager\MediaManager\Platforms\Uap\Media\MediaItemExtensions.cs(30,23,30,40): error CS0246: The type or namespace name 'MediaPlaybackItem' could not be found (are you missing a using directive or an assembly reference?)
> 1>Inrego\XamarinMediaManager\MediaManager\Platforms\Uap\MediaManagerImplementation.cs(36,16,36,27): error CS0246: The type or namespace name 'MediaPlayer' could not be found (are you missing a using directive or an assembly reference?)
> 1>Inrego\XamarinMediaManager\MediaManager\Platforms\Uap\Player\WindowsMediaPlayer.cs(15,69,15,80): error CS0246: The type or namespace name 'MediaPlayer' could not be found (are you missing a using directive or an assembly reference?)
> 1>Inrego\XamarinMediaManager\MediaManager\Platforms\Uap\Video\VideoView.xaml.cs(6,45,6,56): error CS0246: The type or namespace name 'UserControl' could not be found (are you missing a using directive or an assembly reference?)
> 1>Inrego\XamarinMediaManager\MediaManager\Platforms\Uap\Media\StorageFileProvider.cs(37,43,37,65): error CS0246: The type or namespace name 'IStorageItemProperties' could not be found (are you missing a using directive or an assembly reference?)
> 1>Inrego\XamarinMediaManager\MediaManager\Platforms\Uap\Media\StorageFileProvider.cs(55,43,55,65): error CS0246: The type or namespace name 'IStorageItemProperties' could not be found (are you missing a using directive or an assembly reference?)
> 1>Inrego\XamarinMediaManager\MediaManager\Platforms\Uap\Player\WindowsMediaPlayer.cs(42,16,42,27): error CS0246: The type or namespace name 'MediaPlayer' could not be found (are you missing a using directive or an assembly reference?)
> 1>Inrego\XamarinMediaManager\MediaManager\Platforms\Uap\Media\StorageFileProvider.cs(115,62,115,73): error CS0246: The type or namespace name 'StorageFile' could not be found (are you missing a using directive or an assembly reference?)
> 1>Inrego\XamarinMediaManager\MediaManager\Platforms\Uap\Media\StorageFileProvider.cs(115,30,115,42): error CS0246: The type or namespace name 'IInputStream' could not be found (are you missing a using directive or an assembly reference?)
> 1>Inrego\XamarinMediaManager\MediaManager\Platforms\Uap\Player\WindowsMediaPlayer.cs(57,16,57,33): error CS0246: The type or namespace name 'MediaPlaybackList' could not be found (are you missing a using directive or an assembly reference?)
> 1>Inrego\XamarinMediaManager\MediaManager\Platforms\Uap\Video\VideoView.xaml.cs(11,16,11,34): error CS0246: The type or namespace name 'MediaPlayerElement' could not be found (are you missing a using directive or an assembly reference?)
> 1>Inrego\XamarinMediaManager\MediaManager\Platforms\Uap\Player\WindowsMediaPlayer.cs(127,41,127,52): error CS0246: The type or namespace name 'MediaPlayer' could not be found (are you missing a using directive or an assembly reference?)
> 1>Inrego\XamarinMediaManager\MediaManager\Platforms\Uap\Video\VideoView.xaml.cs(10,17,10,35): error CS0246: The type or namespace name 'MediaPlayerElement' could not be found (are you missing a using directive or an assembly reference?)
> 1>Inrego\XamarinMediaManager\MediaManager\Platforms\Uap\Player\WindowsMediaPlayer.cs(132,52,132,72): error CS0246: The type or namespace name 'MediaPlaybackSession' could not be found (are you missing a using directive or an assembly reference?)
> 1>Inrego\XamarinMediaManager\MediaManager\Platforms\Uap\Player\WindowsMediaPlayer.cs(137,62,137,82): error CS0246: The type or namespace name 'MediaPlaybackSession' could not be found (are you missing a using directive or an assembly reference?)
> 1>Inrego\XamarinMediaManager\MediaManager\Platforms\Uap\MediaManagerImplementation.cs(95,19,95,33): error CS0246: The type or namespace name 'DisplayRequest' could not be found (are you missing a using directive or an assembly reference?)
> 1>Inrego\XamarinMediaManager\MediaManager\Platforms\Uap\Player\WindowsMediaPlayer.cs(143,54,143,74): error CS0246: The type or namespace name 'MediaPlaybackSession' could not be found (are you missing a using directive or an assembly reference?)
> 1>Inrego\XamarinMediaManager\MediaManager\Platforms\Uap\Volume\VolumeManager.cs(9,19,9,30): error CS0246: The type or namespace name 'MediaPlayer' could not be found (are you missing a using directive or an assembly reference?)
> 1>Inrego\XamarinMediaManager\MediaManager\Platforms\Uap\Volume\VolumeManager.cs(59,52,59,57): error CS0234: The type or namespace name 'Media' does not exist in the namespace 'Windows' (are you missing an assembly reference?)
> 1>Inrego\XamarinMediaManager\MediaManager\Platforms\Uap\Player\WindowsMediaPlayer.cs(148,63,148,83): error CS0246: The type or namespace name 'MediaPlaybackSession' could not be found (are you missing a using directive or an assembly reference?)
> 1>Inrego\XamarinMediaManager\MediaManager\Platforms\Uap\Volume\VolumeManager.cs(64,51,64,56): error CS0234: The type or namespace name 'Media' does not exist in the namespace 'Windows' (are you missing an assembly reference?)
> 1>Inrego\XamarinMediaManager\MediaManager\Platforms\Uap\Player\WindowsMediaPlayer.cs(153,59,153,79): error CS0246: The type or namespace name 'MediaPlaybackSession' could not be found (are you missing a using directive or an assembly reference?)
> 1>Inrego\XamarinMediaManager\MediaManager\Platforms\Uap\Player\WindowsMediaPlayer.cs(158,41,158,52): error CS0246: The type or namespace name 'MediaPlayer' could not be found (are you missing a using directive or an assembly reference?)
> 1>Inrego\XamarinMediaManager\MediaManager\Platforms\Uap\Player\WindowsMediaPlayer.cs(158,61,158,87): error CS0246: The type or namespace name 'MediaPlayerFailedEventArgs' could not be found (are you missing a using directive or an assembly reference?)
> 1>Inrego\XamarinMediaManager\MediaManager\Platforms\Uap\Player\WindowsMediaPlayer.cs(163,40,163,51): error CS0246: The type or namespace name 'MediaPlayer' could not be found (are you missing a using directive or an assembly reference?)
> 1>Inrego\XamarinMediaManager\MediaManager\Platforms\Uap\Player\WindowsMediaPlayer.cs(214,40,214,60): error CS0246: The type or namespace name 'IMediaPlaybackSource' could not be found (are you missing a using directive or an assembly reference?)
> 1>Inrego\XamarinMediaManager\MediaManager\Platforms\Uap\Player\WindowsMediaPlayer.cs(41,17,41,28): error CS0246: The type or namespace name 'MediaPlayer' could not be found (are you missing a using directive or an assembly reference?)
> 1>Inrego\XamarinMediaManager\MediaManager\Platforms\Uap\Player\WindowsMediaPlayer.cs(56,17,56,34): error CS0246: The type or namespace name 'MediaPlaybackList' could not be found (are you missing a using directive or an assembly reference?)
> 1>Done building project "MediaManager.csproj" -- FAILED.

**Comment by martijn00** [comment]
@Inrego do you have the Windows SDK 10.0.17763 installed?

**Comment by Inrego** [comment]
I thought that was what VS prompted me to install when loading the project. But I installed it now, and it's building.

**Comment by martijn00** [comment]
@Inrego great! Are you going to pick up the other issues you filled out? If you want you can chat to me on the XamarinChat Slack.

**Comment by Inrego** [comment]
Yup, I'm already on it
