### ISSUE TITLE
Android: Streams Exoplayer UnrecognizedInputFormatException

### ISSUE THREAD

**Issue by Suplanus** [Baseflow/XamarinMediaManager#745]
## 🐛 Bug Report

I tried different streaming sources.

#### MP3
https://ia800806.us.archive.org/15/items/Mp3Playlist_555/AaronNeville-CrazyLove.mp3
✅ Works

#### MP3 Stream
http://bob.hoerradar.de/radiobob-live-mp3-hq
❌ Connected but silent

#### AAC
http://www.rockantenne.de/webradio/rockantenne.aac.pls
❌ Exception: 
```
com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor, Ac4Extractor, FlacExtractor) could read the stream.
```

### Expected behavior
Standard streaming formats works

### Reproduction steps

```csharp
await CrossMediaManager.Current.Play(urlFromAbove);
```

### Configuration

**Version:** 1.0

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Suplanus** [comment]
I have also tried from the readme:

```csharp
var mediaItem = await CrossMediaManager.Current.Extractor.CreateMediaItem(urlFromAbove);
mediaItem.MediaType = MediaManager.Library.MediaType.Audio;
```

But the stream is silent then (but without exception).

**Comment by Nagendra574** [comment]
Hi,
   I have a similar issue I am calling AWS Cloud front Video URL please help me how can I play the video.

Thanks in Advance.

**Comment by Suplanus** [comment]
The linked PR is for iOS. This issue is about Android.
Also think it was a typo in the description.
