### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by MrPeppersSayan** [Baseflow/XamarinMediaManager#748]
## 🐛 Bug Report
When the app initialize i got an error: 

System.NotImplementedException
  HResult=0x80004001
  Mensage = This functionality is not implemented in the portable version of this assembly. You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.
  Origin = MediaManager

Or is there anything else am i missing?

### Reproduction steps
1- Fresh proyect of xamarin Forms
2- Install Plugin.MediaManager to all proyects
3- Add the   **CrossMediaManager.Current.Init();** to proyects
4- Compile and execute

### Configuration
Xamarin Forms 4.7.0

**Version:** 1.x

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Install the nuget into all app projects and init from there.
