### ISSUE TITLE
IsPlaying or IsBuffering Binding

### ISSUE THREAD

**Issue by melakhvision** [Baseflow/XamarinMediaManager#761]
## 💬 Question
Hello
I just need help. How can I bind the IsPlaying or IsBuffering to the activity indicator? I try a lot but don't find a solution.

**Comment by melakhvision** [comment]
I tried 
bool IsBuffering = CrossMediaManager.Current.IsBuffering();
and set the indicator to be visible when buffering but it not working.
I set it up like this 
        public void Buffering()
        {


            if (IsBuffering == true)

            {
                 BufferingActivity.IsVisible = true;
                 PlayerContent.IsVisible = false;
               
            }
            else
            {
                PlayerContent.IsVisible = true;
                BufferingActivity.IsVisible = false;
            }
            
        }
Can anyone help ?
Are the bool of the mediamanager state working ?

**Comment by EddieNoureddine** [comment]
you need to update the UI 
use OnPropertyChanged(nameof(YourPropertyGoesHere));
