### ISSUE TITLE
`Extractor.GetMediaType` Returns `Default` for Azure Media Services Streaming URLs

### ISSUE THREAD

**Issue by brminnick** [Baseflow/XamarinMediaManager#768]
### Incorrect MediaType for Azure Media Services URLs

When an Azure Media Services URL is passed into `CrossMediaManager.Current.Extractor.GetMediaType`, it always returns `MediaType.Default`.

```csharp
var mediaType = CrossMediaManager.Current.Extractor.GetMediaType("https://amssamples.streaming.mediaservices.windows.net/91492735-c523-432b-ba01-faba6c2206a2/AzureMediaServicesPromo.ism/manifest(format=m3u8-aapl)");
// mediaType is MediaType.Default
// should be MediaType.Hls
```

### Azure Media Services Info

Azure Media Services uses the following suffixes to denote the format of the video:
- HLS: `https://[video url]/Manifest(format=m3u8-aapl)` 
- DASH: `https://[video url]/Manifest(format=mpd-time-csf)`

From the [Azure Media Services Docs](https://docs.microsoft.com/azure/media-services/previous/media-services-deliver-content-overview?WT.mc_id=mobile-0000-bramin):
> - HTTP Live Streaming (HLS) - add "(format=m3u8-aapl)" path to the "/Manifest" portion of the URL to tell the streaming origin server to return back HLS content for consumption on Apple iOS native devices (for details, see locators and URLs),
> - MPEG-DASH - add "(format=mpd-time-csf)" path to the "/Manifest" portion of the URL to tell the streaming origin server to return back MPEG-DASH (for details, see locators and URLs),

When this url is passed into `VideoView.Source`, AzureMediaServices always returns its `MediaType` as `MediaType.Default`

Here is an example URL from a video uploaded to Azure Media Services. (We can confirm it's valid by copy/pasting it into a Safari web browser):
https://amssamples.streaming.mediaservices.windows.net/91492735-c523-432b-ba01-faba6c2206a2/AzureMediaServicesPromo.ism/manifest(format=m3u8-aapl)

### Android Streaming Errors

On Android, this causes the following error, which is happening because [Android is trying to play an m3u8 file, and it needs an HLS media source](https://stackoverflow.com/a/60611780/5953643)
```
[ExoPlayerImplInternal] Source error
[ExoPlayerImplInternal]   com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor, Ac4Extractor, FlacExtractor) could read the stream.
[ExoPlayerImplInternal]       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractorHolder.selectExtractor(ProgressiveMediaPeriod.java:1096)
[ExoPlayerImplInternal]       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:975)
[ExoPlayerImplInternal]       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
[ExoPlayerImplInternal]       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
[ExoPlayerImplInternal]       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
[ExoPlayerImplInternal]       at java.lang.Thread.run(Thread.java:923)
```

### Expected behavior

```csharp
var mediaType = CrossMediaManager.Current.Extractor.GetMediaType("https://amssamples.streaming.mediaservices.windows.net/91492735-c523-432b-ba01-faba6c2206a2/AzureMediaServicesPromo.ism/manifest(format=m3u8-aapl)");
// mediaType should be MediaType.Hls
```

### Reproduction steps

1. Download/Clone [AzureMediaServicesSampleApp](https://github.com/brminnick/AzureMediaServicesSampleApp)
2. In Visual Studio, open AzureMediaServicesSampleApp.sln
3. In Visual Studio, set the build configuration to AzureMediaServicesSampleApp.Droid
4. In Visual Studio, build/deploy `AzureMediaServicesSampleApp.Droid` to an Android Device
5. On the Android Device, select `Watch in Native Video Player`
6. On the Android Device, confirm the video does not play
7. In Visual Studio, in the Application Output, confirm the following error logs:
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/13558917/97746693-06739c80-1aa8-11eb-99ab-5bb351bea168.png">

### Configuration

**Version:** Plugin.MediaManager.Forms v 1.0.4

**Platform:** 
- [x] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by brminnick** [comment]
I have a hunch that the logic in `public virtual string GetFileExtension(string fileName)` may be the root cause:
https://github.com/Baseflow/XamarinMediaManager/blob/bc9eb7945d265a2c624fa3df16962d599da986b4/MediaManager/Media/MediaExtractorBase.cs#L235-L256

For example, when I pass in the Azure Media Services URL to `GetFileExtension`, it returns `.ism`:

```csharp
var fileExtension = CrossMediaManager.Current.Extractor. GetFileExtension(https://amssamples.streaming.mediaservices.windows.net/91492735-c523-432b-ba01-faba6c2206a2/AzureMediaServicesPromo.ism/manifest(format=m3u8-aapl));
// fileExtension is `.ism`
```

**Comment by martijn00** [comment]
@brminnick thanks! This should be fixed in https://github.com/Baseflow/XamarinMediaManager/commit/07009685978fc4aff010f657adf6695de686cfd2 and release 1.0.6

**Comment by brminnick** [comment]
Thanks Martijn!!!

I just installed v1.0.6 and confirmed everything works great!!

https://github.com/brminnick/AzureMediaServicesSampleApp
