### ISSUE TITLE
Init does not work anywhere

### ISSUE THREAD

**Issue by chuckgiddens** [Baseflow/XamarinMediaManager#769]
## 🐛 Bug Report
Calling INIT any where cases crash

![image](https://user-images.githubusercontent.com/5237149/99437601-b33f7d80-28e0-11eb-9d4b-af961a3949c3.png)

### Expected behavior
Not to crash
### Reproduction steps
Use your library and follow your installation instructions
### Configuration
Windows 10, Visual Studio 2019 Pro, XamForms V.4.8.0.1364
**Version:** 1.0.4

**Platform:** 
- [x] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by chuckgiddens** [comment]
BTW, if I add CrossMediaManager.Current.Init(this), I get a compile error.  Not allowing me to pass in THIS in Android.

**Comment by Immons** [comment]
@chuckgiddens have you added same version of package to your platform project?

**Comment by chuckgiddens** [comment]
Yes....

**Comment by martijn00** [comment]
You need to target android 10
