### ISSUE TITLE
Plugin.MediaManager.Forms is not working in xamarin uwp

### ISSUE THREAD

**Issue by sreejithsree139** [Baseflow/XamarinMediaManager#777]
Reference: https://docs.microsoft.com/en-us/answers/questions/198678/xamarin-forms-issue-with-mediaelement-audio-playin.html

I am using `Plugin.MediaManager.Forms` for playing audio. It is working fine in android and ios. But in windows, the app is breaking with `System.NotImplementedException.`.

![49474-capture](https://user-images.githubusercontent.com/65383896/102863982-64de4b00-4459-11eb-9c79-8753b8d6d0c7.png)
 
**Plugin.MediaManager.Forms: 1.0.7
Xamarin Forms: 4.8.0.1821**

Uploaded a sample project [here](https://drive.google.com/file/d/1SOZwP89uWhJe20oKAlQO8WXuzqBU53hk/view?usp=sharing) for reference.

**Comment by martijn00** [comment]
You need to target the correct windows sdk version

**Comment by sreejithsree139** [comment]
@martijn00 What is the correct windows versions, I am adding mine below:

![Capture](https://user-images.githubusercontent.com/65383896/102976038-f8318200-4526-11eb-8218-6d16ac6e0c83.PNG)

Also, I have added the "Background Media Playback", "Internet", "Music Library" and "Videos Library" in the Package.appxmanifest under capabilities.

**Xamarin Forms: 4.8.0.1821
Visual Studio: 16.7.0**

What else I am missing? Could you please point that?

**Comment by martijn00** [comment]
Min version should be uap10.0.17763

**Comment by sreejithsree139** [comment]
Changed the min version, but a new error is showing. I can't figure out the reason, can you have a look?
![Capture](https://user-images.githubusercontent.com/65383896/102992685-acd89d00-4541-11eb-89a4-ff4f6d6fa719.PNG)
