### ISSUE TITLE
MediaItemChanged not fired

### ISSUE THREAD

**Issue by Hackmodford** [Baseflow/XamarinMediaManager#780]
## 🐛 Bug Report

When I start playing an item, MediaItemChanged is not fired.

### Expected behavior

Event MediaItemChanged is fired.

### Configuration

**Version:** 1.0.7

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Fixed in https://github.com/Baseflow/XamarinMediaManager/commit/bb11f2da01c1e1a782665efa37e7ead681435edd
