### ISSUE TITLE
After Finished Playing Local File it Gets Stuck on Buffering and Doesn't Wanna Play Again on Real IPhone

### ISSUE THREAD

**Issue by robertvo** [Baseflow/XamarinMediaManager#807]
## 🐛 Bug Report

playback doesn't start after calling CrossMediaManager.Current.Play() after local track has finished playing (iOS).

The player state is stuck at "Buffering" and never plays. Only on Real IPhone.

### Expected behavior
After calling CrossMediaManager.Current.Play() track should start playing again.

This works in IOS simulator, doesn't work (SOMETIMES) or real IPhone SE 2020.  

### Reproduction steps
Play any mp3 track from a local file
Let it finish playing to the end
Wait a bit and attempt to play it again with CrossMediaManager.Current.Play()

### Configuration

**Version:** 1.08

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by rkaradas** [comment]
I have the same issue, but it even happens when I navigate through the queue (next/preview-methods). 
I was testing on real device and now cross checked the behaviour on simulator. It is really an issue on real devices.

**Comment by robertvo** [comment]
> I have the same issue, but it even happens when I navigate through the queue (next/preview-methods).
> I was testing on real device and now cross checked the behaviour on simulator. It is really an issue on real devices.

any ideas for a workaround?

**Comment by rkaradas** [comment]
Sorry for the late reply. Unfortunately I have no idea for a workaround, but after installing all the latest updates (xamarin, etc.), the problem seems to be gone.
