### ISSUE TITLE
Notification image not showing image from URL on iOS

### ISSUE THREAD

**Issue by MikaelStalvik** [Baseflow/XamarinMediaManager#808]
## 🐛 Bug Report

When playing a track and assigning a valid image to the MediaItem, the image is not shown on iOS.
On Android it is shown properly.

### Expected behavior

The image from the URL should be show.

### Reproduction steps

Play an MP3 from a stream:

`
            await CrossMediaManager.Current.Play(new MediaItem
            {
                MediaUri = url,
                Title = track.Title,
                Artist = track.Artist,
                Author = string.Empty,
                Album = track.Album,
                DisplayImageUri = imgUrl,
                AlbumImageUri = imgUrl,
                ImageUri = imgUrl
            });
`

url = The url to the MP3 file.
imgUrl = The url to the image.

Both urls uses http:// without any authentication.

### Configuration

**Version:** 1.08

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
http is not allowed unless you add it in your manifest. See the docs.
