### ISSUE TITLE
Can't play media on IOS

### ISSUE THREAD

**Issue by eramrit78** [Baseflow/XamarinMediaManager#831]
## 🐛 Bug Report

I am trying to play m3u8 URL on ios but if failed. i am using latest xamarin form 5.x update 2083.It works well on android.

### Expected behavior
It should play on IOS

### Configuration

**Version:** 1.x
1.09

**Platform:** 
- [x] :iphone: iOS
![Screenshot (12)](https://user-images.githubusercontent.com/48124576/128215781-a7ebfe10-142f-4f93-8c55-00c91c10d627.png)

- [ ] :robot: Android
- [ ] :monkey: Xamarin.Forms

**Comment by isax5** [comment]
Looks like it affects some iOS versions only
I can play everything in iOS 14.5 but it doesn't work in iOS 11 and 12
