### ISSUE TITLE
Playing from a URL without .mp3 extention at the end

### ISSUE THREAD

**Issue by Muhammad-Radwan** [Baseflow/XamarinMediaManager#836]
## 💬 Questions and Help
Hello everyone
I'm developing an app to live stream audio from a radio station. In my server I'm using RadioBoss as a media player and IceCast to make a live stream URL. I've tested the URL on mobile's internet browser and it's working perfectly. When I'm trying to implement that in Xamarin.Forms app (I'm using the Plugin.MediaManager Nuget) and my URL looks like  "http://192.168.204.68:8000/live" but when I press play nothing happens, I tried another URL which has the "mp3" extension (https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3) for instance and it's working just fine.
Can anybody help please.

**Comment by abri-k** [comment]
I have the same problem. Not worked for http url but  worked for https

**Comment by martijn00** [comment]
Read the Readme for http. Look into IMediaItem for mp3 without extension support.
