### ISSUE TITLE
Why not work for http url?

### ISSUE THREAD

**Issue by abri-k** [Baseflow/XamarinMediaManager#847]
## 🐛 Bug Report

I try play http file: http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4
It is not worked.

But https file https://ia800806.us.archive.org/15/items/Mp3Playlist_555/AaronNeville-CrazyLove.mp3
It is worked

It is true for mp3, mp4 files
I use code 
await CrossMediaManager.Current.Play(audioUrl);

**Version:** 1.0.9

**Platform:** 
- [ ] :robot: Android

**Comment by martijn00** [comment]
See readme.
