### ISSUE TITLE
UWP: System.NotImplementedException in MediaManager.dll

### ISSUE THREAD

**Issue by tungox6** [Baseflow/XamarinMediaManager#865]
## 🐛 Bug Report

My first try with MediaManager: Works well with Android. On UWP, I got NotImplementedException when calling CrossMediaManager.Current.Init()

### Configuration

**Version:** 1.1.1

**Platform: (Xamarin UWP Project)** 
- Xamarin.Forms: 5.0.0.2478
- Xamarin.Essentials: 1.7.3
- Microsoft.NETCore.UniversalWindowsPlatform: 6.2.14

**Comment by 0xJins** [comment]
@tungox6 I got the same problem! But I fixed it. I change the platform minimum target version of uwp project >= 10.0.18362.0!
