### ISSUE TITLE
only black screen xamarinmediamanager project

### ISSUE THREAD

**Issue by ligeirow** [Baseflow/XamarinMediaManager#871]
could you help me please i try several times but only black screen i will share project

**Comment by ligeirow** [comment]
[crossmedia4_2.zip](https://github.com/Baseflow/XamarinMediaManager/files/9283508/crossmedia4_2.zip)

**Comment by ligeirow** [comment]
what is wrong ? because not work crossmedia manager only black screen

**Comment by ligeirow** [comment]
https://drive.google.com/file/d/1aSH9Y9PlBQefZokC1sMQqFUTAo1MGdTL/view?usp=sharing 

Project only black screen

**Comment by Shayether** [comment]
@ligeirow Facing the same issue. Did you found any workarounds
