### ISSUE TITLE
Plugin Not Play on android sdk 12

### ISSUE THREAD

**Issue by MohammedMahmoud01** [Baseflow/XamarinMediaManager#876]
##I Have Created an xamarin forms app with xamarin media manger  to play hls videos.
it just play perfectly on android blow 12 sdk but android sdk 12 and above not working at all. 
any one Know Solution

**Comment by carlosanpardo** [comment]
Hello. Try add the below code before start the player

`CrossMediaManager.Current.Speed = 1F;`

**Comment by okains** [comment]
That workaround is a lifesaver @carlosanpardo !

**Comment by carlosanpardo** [comment]
Any idea to launch the top bar with the data of the stream?

**Comment by okains** [comment]
Not sure what you mean, what is the ' top bar ' ?

**Comment by gemelo-hh** [comment]
> Hello. Try add the below code before start the player
> 
> `CrossMediaManager.Current.Speed = 1F;`

Hi, yeah, that helps me, too, after hourse of debugging... maybe that would be worth mentioned on startpage/howto for android...
Lots of greets, your doing a great job, thanks for all!
Thies

**Comment by janwiebe-jump** [comment]
@carlosanpardo At what time do you call this line? 
```CrossMediaManager.Current.Speed = 1F;```
When I called soon after `CrossMediaManager.Current.Init()` it tells me that the MediaSession hasn't been setup yet.

**Comment by bitshftr** [comment]
> @carlosanpardo At what time do you call this line? `CrossMediaManager.Current.Speed = 1F;` When I called soon after `CrossMediaManager.Current.Init()` it tells me that the MediaSession hasn't been setup yet.

I'd like to know where to put this magic line of code also.

**Comment by cklenk** [comment]
I put it in my PCL class right before calling play.
![image](https://user-images.githubusercontent.com/12185742/208474514-8d6eacb6-2f95-4b6f-833f-89417cda3853.png)
This seems to be working. With Google requiring targeting sdk 31+ this should be addressed soon.

**Comment by c0demak3r** [comment]
Thank you @carlosanpardo your suggestion of adding **CrossMediaManager.Current.Speed = 1F;** solved it for my non-profit's app on Android 12 and 13!
