### ISSUE TITLE
Version 1.1.1 does not create player in Notification Manager on Android 12

### ISSUE THREAD

**Issue by copang** [Baseflow/XamarinMediaManager#877]
## 🔙 Regression

I'm using version 1.1.1 and it can work with Android 12, however I noticed that it doesn't create player in notification manager like previous versions (1.0.9), this results in audio only being playable in background about 15-30m and then will be stopped.
Devices running Android lower than 12 still work properly. This issue only occurs on devices running Android 12.

### Old (and correct) behavior
1. Play audio
2. Go to background
3. There are media player in Notification Manager -> can play audio all night

### Current behavior
1. Play audio
2. Go to background
3. No media player in Notification Manager  -> audio stop after 15-30m

### Configuration
Xamarin.Forms 5.0.0.2515
Plugin.MediaManager.Forms 1.1.1

**Version:** 1.1.1

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by arahmancsd** [comment]
same here, updated to Android 12. Got the player playing the media, but I  can't see anything in the notification area.
Also, [Support Android target level api 31](https://github.com/Baseflow/XamarinMediaManager/issues/866) #866 doesn't mention anything at the end regarding the issue.

**Comment by ArchangelWTF** [comment]
It's probably due to lie in the MediaBrowserService not creating the notification correctly due to Google having removed parts of code there that initialize the NotificationListener which in term starts the notification.

**Comment by copang** [comment]
Thanks @ArchangelWTF for fixing it, but with current version (using .net 6) how can I use it for Xamarin Forms? If yes hope you give me some tutorial.
Thank you very much!

**Comment by ArchangelWTF** [comment]
If you need backwards compatibility for now for a Xamarin Forms app your best bet would be to create a Fork branched off of this commit https://github.com/Baseflow/XamarinMediaManager/commit/24cf94f9a66a7fe6b3daf73198cb93fbe77745e8 and manually do the change my PR did to the MediaBrowserService and then compile it for yourself to use in XF

**Comment by arahmancsd** [comment]
@ArchangelWTF I forked the recent changes and packed the required libs with your changes. It is still not working in Android 12.

**Comment by janwiebe-jump** [comment]
@arahmancsd I did more or less the same at https://github.com/janwiebe-jump/XamarinMediaManager/tree/xamarin-android-12
It does create the notification on playing on my Android 13 phone.

**Comment by copang** [comment]
@ArchangelWTF, I tried your suggestion and found that the PlayerNotificationManager.Builder method needed to pass 4 parameters, so I fixed it as follows:
`
PlayerNotificationManager = new Com.Google.Android.Exoplayer2.UI.PlayerNotificationManager.Builder(
                this,
                ForegroundNotificationId,
                ChannelId,
                MediaDescriptionAdapter)
                .SetNotificationListener(NotificationListener)
                .Build();
`
In addition, I had some other errors, but when I removed the targets xamarin.mac20, xamarin.tvos10, tizen40, I was able to build the package for Forms.
But it still can't create player in notification manager on Android 12 devices. Am I doing something wrong?

**Comment by copang** [comment]
@janwiebe-jump, I tried using your version and to be able to build I also had to remove some targets like in the above comment (I don't know if it caused any errors). However, it still doesn't create player in notification manager, I tested it on Oneplus and Xiaomi phones running Android 12.
If you have successfully tested it, can you send me a copy of the package you used?
Thanks!

**Comment by janwiebe-jump** [comment]
hmm, my version doesn't work either unfortunately. Playing doesn't start.

**Comment by copang** [comment]
@janwiebe-jump you can try workaround from #876

**Comment by ArchangelWTF** [comment]
@sschaub That exception is very similar to the one thrown here: https://github.com/Baseflow/ExoPlayerXamarin/issues/137 which I've put a workaround for in that issue, I suppose you could try that or something similar and see if it works without throwing that exception then.

**Comment by sschaub** [comment]
@ArchangelWTF Thanks for the tip! I really appreciate your quick response.

I added the methods your workaround suggests to `XamarinMediaManager\MediaManager\Platforms\Android\Player\PlayerEventListener.cs` and was able to play an audio track successfully. I also noticed that a foreground service was started, which was very encouraging. However, when I added a `MediaButtonReceiver` to the AndroidManifest.xml to handle media button presses, the application crashed on startup in MediaBrowserService.cs (PrepareMediaSession()) on the line

```
var mediaSession = MediaManager.MediaSession = new MediaSessionCompat(this, nameof(MediaBrowserService));
``` 

with the error:

```
Java.Lang.IllegalArgumentException: 'com.companyname.formsdemo: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent ...
```

This is the same error that is causing the problem with XMM 1.1.1. Not sure what to do about it in this particular scenario, since `MediaSessionCompat` is in the Android libraries... I don't see a place to add the required flag near this line.

Also, I noticed that video playback is not working. I hear the audio of the video, but the video itself does not appear.

**Comment by martijn00** [comment]
I've commited some fixes based on this. At least it compiles now. It would be great if someone can write the renderer to Maui.

**Comment by irediaes** [comment]
Hello @martijn00 @ArchangelWTF 

Please, our app in production is current crashing for android 12+ users.

Throwing this error:

```
Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent ...
```

Please, I am willing to pay to have a NuGet version that fixed this. It's super urgent.

I already tried building this but I am getting compile error on my Mac.

Looking forward to your positive feedback.
Thank you!

**Comment by arahmancsd** [comment]
@irediaes If you are not concerned about the notification manager, things should be straightforward. I did update it without having the notification manager yet but working on my local version to solve the notification manager issue.

If you have a custom renderer or wherever you use those two flags in your Android Project (I used it in several places for notifications) So you should change them to the followings;

```
var pendingIntentFlags = (Build.VERSION.SdkInt >= BuildVersionCodes.S)
                ? PendingIntentFlags.UpdateCurrent | PendingIntentFlags.Mutable
                : PendingIntentFlags.UpdateCurrent;
var pendingIntent = PendingIntent.GetBroadcast(AndroidApp.Context, 0, intent, pendingIntentFlags);
```

**Comment by irediaes** [comment]
@arahmancsd 

I am having compiling issues in the building local NuGet version. 

Please can you share the compile NuGet of this plugin if you have one.

**Comment by irediaes** [comment]
Update:

I did some workaround and I was able to by-pass this issue with same Nuget version that was throw the error.

**Comment by irediaes** [comment]
Currently an issue with play longer audio tracks that is more than 15-30min duration. Everything still points back to the plugin.

**Comment by zohaibshahzad1990** [comment]
This I was doing, directly fixing the issue by referencing the library as a project.
@arahmancsd doing.

**Comment by irediaes** [comment]
@zohaibshahzad1990 I did a workaround on the app that got it working instead of the app crashing instantly when launched. At least users can use the app and play the audios.

**Comment by sschaub** [comment]
I have had some success creating a patched version of XMM based on commit https://github.com/Baseflow/XamarinMediaManager/commit/24cf94f9a66a7fe6b3daf73198cb93fbe77745e8 that seems to work on Android 12. Here are the specific changes I made:

https://github.com/sschaub/XamarinMediaManager/commit/a04a73bc5908e8db3aceea7fb589b372d982d422

@martijn00, if you wanted to create a nuget release that would allow current Xamarin users to get their projects working with Android 12+, if you created a branch at that commit, I could submit a PR.

**Comment by copang** [comment]
@sschaub I think a lot of people are still using Xamarin while waiting for MAUI to be more stable, so it would be great if you could update this package for Xamarin for about 6-12 months.

**Comment by janwiebe-jump** [comment]
@sschaub I have been working on the ExoPlayer bindings for Xamarin for the latest version of ExoPlayerXamarin (2.18.7) at https://github.com/janwiebe-jump/ExoPlayerXamarin
I got the basics of MediaManager (playing audio) working with this version as well.
Maybe it can be of help for you.

**Comment by sschaub** [comment]
@copang I agree that it would be very helpful if this project could support Xamarin at least until its announced end of life of May 1, 2024 (https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin). However I don't know what would be involved in having one code base support both Xamarin and MAUI. One issue is that current versions of the ExoPlayer bindings for Xamarin are compatible only with MAUI.

**Comment by ArchangelWTF** [comment]
@sschaub I'm currently working on a way to make the ExoPlayer bindings from the main repository build for both MAUI and MonoAndroid at the moment so that there shouldn't be need for any forks of that repository to keep updating ExoPlayer, as for how such backwards compatibility could be implemented in XamarinMediaManager I would have no idea.

**Comment by sschaub** [comment]
@ArchangelWTF That's great news!

**Comment by ArXamB** [comment]
Did anyone Figure out how to actually create player notification for android 12+ ?

**Comment by EchoSKSh** [comment]
@sschaub @ArchangelWTF  So the version 1.2.0 only works with maui app ?. Currenlty i am having a issue with verison 1.1.1 it is not creating the player in notification panel do you have any idea ? Can you please guide me on how to fix this

**Comment by sschaub** [comment]
@EchoSKSh @ArXamB I was able to solve the problem by forking the XMM project and patching it. Here is my patched version:

https://github.com/sschaub/XamarinMediaManager/commits/android12-patch-with-exoplayer2.14

**Comment by EchoSKSh** [comment]
@sschaub Greetings. Thank you so much for the awesome work. I tried to add a very simple project to you patched version it works fine 
https://github.com/EchoSKSh/MediaManagerCustomized

how ever when i, get the dlls and include in a project outside (same as the attached project) i can see only a black video view 
https://github.com/EchoSKSh/MediaManagerTestApp

Not sure what i am doing wrong here Could you please guide me on this

**Comment by abdoutech93** [comment]
https://github.com/Baseflow/XamarinMediaManager/issues/866#issuecomment-1463841140

**Comment by abdoutech93** [comment]
> @EchoSKSh @ArXamB I was able to solve the problem by forking the XMM project and patching it for Xamarin. Here is my patched version:
> 
> https://github.com/sschaub/XamarinMediaManager/commits/android12-patch-with-exoplayer2.14

even with this patch, still not working here is the details #893

**Comment by Shayether** [comment]
@abdoutech93 I was able to fix this issue and it is working fine for me. You can check this repo - https://github.com/EchoSKSh/MediaManagerCustom

**Comment by abdoutech93** [comment]
@EchoSKSh I think this repo is private !! I would also specify that I'm trying to play an **_hls stream_**.

**Comment by abdoutech93** [comment]
> @janwiebe-jump, I tried using your version and to be able to build I also had to remove some targets like in the above comment (I don't know if it caused any errors). However, it still doesn't create player in notification manager, I tested it on Oneplus and Xiaomi phones running Android 12.
> If you have successfully tested it, can you send me a copy of the package you used?
> Thanks!

Same, any update about it !!!?

**Comment by janwiebe-jump** [comment]
I use my own branch currently, that is suitable for targetSdk 32:
https://github.com/janwiebe-jump/XamarinMediaManager/tree/feature/2023-xamarin-android-12

Not sure if HLS is working though, I only use it to play MP3 files

**Comment by BajakiGabesz** [comment]
You could use mine as well. It also supports HLS but is based on ExoPlayer 2.14.6 at the moment and it is working fine on Android 12 and earlier.
I used part of the solution that @janwiebe-jump did.
I also merged most of the fixes which arrived in the develop branch in the meantime and also have a workaround for issue #894.

You can find it here: https://github.com/BajakiGabesz/XamarinMediaManager/tree/xamarin-1.1.3

**Comment by martijn00** [comment]
If anyone has done fixes, please contribute back as well so the MAUI version stays up-to-date.

**Comment by ArchangelWTF** [comment]
@martijn00 Maybe it would be an idea to create a Xamarin based branch on XamarinMediaManager so that we can merge all these forks we have floating around into one single codebase under one single nuget package much like we have done for ExoPlayer?

**Comment by SoftwareMagicIT** [comment]
I've read everything carefully, I'm trying everything. With XMM for Xamarin there is no way to have the notification. I converted one of my projects to MAUI and almost everything works with latest github 1.2.2 source codes changes. Almost because the notification works, the app plays the sound but there is a but that I can't find a solution to. The problem is that if the app stays on top, even if you turn off the screen, it works. If it goes into the background and the screen stays on it works. If it goes into the background and the screen turns off, the app is killed by Android 12, the notification stays active but it doesn't do anything anymore! I don't get a foot out of it. Obviously I won't explain how I did the implementation at the time, because before discovering Xamarin Media Manager I used the system player, so the part of the code that plays is in the mainactivity and I invented the way to communicate the app Xamarin Form with the native part and vice versa even though Microsoft for Xamarin claimed that this was not possible. Now I have this stupid problem that I don't solve and for each (failed) attempt I have to wait those 5 minutes hoping that the app doesn't get terminated. Does anyone have any ideas?

**Comment by martijn00** [comment]
Fine with me!

**Comment by 15mgm15** [comment]
> Update:
> 
> I did some workaround and I was able to by-pass this issue with same Nuget version that was throw the error.
> 
> I was able to build for target SDK API 31+

Can you share me your workarounds?
