### ISSUE TITLE
VideoView Playback controls not showing up on iOS 16

### ISSUE THREAD

**Issue by KevinHu-au** [Baseflow/XamarinMediaManager#879]
The VideoView control is not showing the Playback controls on iOS 16 (with the `ShowControls` set to true).
The control works well on the previous iOS versions.
![iPhone12 15 6 1](https://user-images.githubusercontent.com/8989917/196836517-598f2466-9ffc-4a36-901b-c8a8c1f1a744.PNG)

![Simulator iPhone 14 16 0](https://user-images.githubusercontent.com/8989917/196836553-dc2e9d49-6023-45cb-bfb6-e01560a0fa6c.png).

The environments:
Xamarin.Forms: 5.0.0.2515
Plugin.MediaManager: 1.1.1
Xamarin.iOS: 16.0.0.72

**Comment by fbcom92** [comment]
Hi, same problem there, no controls for Ios16.
